### ISSUE TITLE
Issues with the std feature

### ISSUE THREAD

**Issue by est31** [RustCrypto/traits#10]
I have two issues with the std feature:

1. it is turned off by default. You have to turn it on manually. While optional no_std support is great, I think more people have std than have no_std, so I think it should be a default enabled feature.
2. the hasher crates don't expose the std features themselves. So there is no real way of enabling it except depending on the digest trait yourself and enabling it :/.

I'm not a fan of all of the api guidelines, but this issue is well described by them: https://github.com/rust-lang-nursery/api-guidelines/blob/5ac0bd004341f6d90f43cd7c325fe845e904c477/src/naming.md#feature-names-are-free-of-placeholder-words-c-feature

**Comment by newpavlov** [comment]
I thought about making `std` default feature, but decided against it, as it infects all downstream crates with `default-features = false` and `digest/std` features. I don't think that one additional string in the `Cargo.toml` for crate users when they need `std::io` functionality outweighs increased complexity for `no_std` crates.

@tarcieri 
Your opinion?

**Comment by tarcieri** [comment]
I'm ok with an enabled-by-default `std` feature, so long as the API itself doesn't gain important functionality that requires `std`

**Comment by newpavlov** [comment]
Fixed with `digest v0.8`. Now `std` feature is enabled by default for hash crates, but still disabled by default for `digest` crate.
