### ISSUE TITLE
How to implement CoreProxy

### ISSUE THREAD

**Issue by agostbiro** [RustCrypto/traits#1028]
Hello,

I'm in the process of upgrading the [hashers in bitcoin-rs](https://github.com/summa-tx/bitcoins-rs/blob/fef2aa37962d3ed13d1905166aba2ea9d4ca2cec/core/src/hashes/mod.rs#L74) for `digest = 0.10`. I've ran into an issue, where the Secp256k1 ECSDA [`DigestSigner`](https://docs.rs/k256/latest/k256/ecdsa/struct.SigningKey.html#impl-DigestSigner%3CD%2C%20Signature%3CSecp256k1%3E%3E) requires the [`digest::core_api::CoreProxy`](https://docs.rs/digest/0.10.3/digest/core_api/trait.CoreProxy.html) trait, but [`CoreProxy`](https://docs.rs/digest/0.10.3/src/digest/core_api/wrapper.rs.html#253) [requires](https://docs.rs/digest/0.10.3/src/digest/core_api/wrapper.rs.html#253) the `digest::core_api::wrapper::sealed::Sealed` trait which is private, so I can't pass the custom hashers to a `DigestSigner`.

This is my code:

```rust
impl digest::core_api::wrapper::sealed::Sealed for Hash256 {}

impl digest::core_api::CoreProxy for Hash256 {
    type Core = sha2::Sha256::Core;
}
```

that errors with:

```
error[E0603]: module `wrapper` is private
  --> core/src/hashes/mod.rs:91:24
   |
91 | impl digest::core_api::wrapper::sealed::Sealed for Hash256 {}
   |                        ^^^^^^^ private module
   |
```

I'm wondering if there is a solution to this that I'm overlooking or if you'd accept a PR to expose `digest::core_api::wrapper::sealed::Sealed` along with `digest::core_api::CoreProxy`?

**Comment by tarcieri** [comment]
`digest::core_api::wrapper::sealed::Sealed` is a sealed trait which is unfortunately leaking out into the public API.

I'm not the primary author of the `digest` crate and I still find these kinds of errors confusing myself. I think the issue here is you need to use [`CoreWrapper`](https://docs.rs/digest/latest/digest/core_api/struct.CoreWrapper.html).

Perhaps we can discuss on a relevant issue instead of here, but perhaps instead of `DigestSigner` you could use the low-level [`SignPrimitive`](https://docs.rs/ecdsa/latest/ecdsa/hazmat/trait.SignPrimitive.html) trait instead so you don't need to implement your own wrapper types.

I think the bounds on `DigestSigner` might also be more restrictive than necessary which is something we should separately investigate.

**Comment by agostbiro** [comment]
Thanks, I wasn't familiar with the sealed trait pattern. 

I can't  implement `CoreWrapper` unfortunately, because if I do, I also need `CoreProxy` to get the `Core` type, but that's a sealed trait. If understand correctly the purpose of the sealed trait is to hide unstable features, but since the crate is on a `0.x` version, maybe it'd be ok to expose it even if you have to break it later?

Anyway, I managed to implement a Bitcoin-style double SHA256 that can be passed to a `DigestSigner` by reimplementing [`Sha256VarCore`](https://docs.rs/sha2/latest/sha2/struct.Sha256VarCore.html) with the following change:

```rust
pub struct DoubleHash256VarCore(Sha256VarCore);

impl VariableOutputCore for DoubleHash256VarCore {

    /// Perform double hash on finalization
    #[inline]
    fn finalize_variable_core(&mut self, buffer: &mut Buffer<Self>, out: &mut Output<Self>) {
        Sha256VarCore::finalize_variable_core(&mut self.0, buffer, out);
        let double_hash = Sha256::new_with_prefix(*out);
        FixedOutput::finalize_into(double_hash, out);
    }
}
```

and then exposing it as

```rust
pub type DoubleHash256 = CoreWrapper<CtVariableCoreWrapper<DoubleHash256VarCore, U32>>;
```

to get all the traits that `CoreWrapper` implements (including the sealed `CoreProxy`). 

There is a full example here: https://github.com/agostbiro/double-sha256/blob/main/src/lib.rs

I'm still a bit uneasy about this, because I have no experience implementing cryptographic primitives, but I'm more comfortable with it than using [`SignPrimitive`](https://docs.rs/ecdsa/latest/ecdsa/hazmat/trait.SignPrimitive.html) which is marked as hazmat. 

Do you think `DoubleHash256VarCore` is a reasonable solution?

---

Btw I also looked into relaxing the bounds on `DigestSigner`, and it turns out that the `signature` crate only [requires](https://docs.rs/signature/latest/src/signature/signer.rs.html#75-91) a `Digest`. The `CoreProxy` trait bound for `DigestSigner` is only introduced in [`k256::ecdsa::SigningKey`](https://docs.rs/k256/latest/src/k256/ecdsa/sign.rs.html#101-118):

```rust
impl<D> DigestSigner<D, Signature> for SigningKey
where
    D: CoreProxy + Digest + FixedOutput<OutputSize = U32>,
    D::Core: BlockSizeUser
        + BufferKindUser<BufferKind = Eager>
        + Clone
        + Default
        + FixedOutputCore
        + HashMarker
        + OutputSizeUser<OutputSize = D::OutputSize>,
    <D::Core as BlockSizeUser>::BlockSize: IsLess<typenum::U256>,
    Le<<D::Core as BlockSizeUser>::BlockSize, typenum::U256>: NonZero,
```

I've tried and `k256::ecdsa::SigningKey` also compiles with these trait bounds:

```rust
impl<D> DigestSigner<D, Signature> for SigningKey
where
    D: Digest + FixedOutput<OutputSize = U32>,
```

so I guess `D: CoreProxy` is only needed for the `HashMarker` and `U256` bounds. Should I open an issue about this in the `elliptic-curves` repo?

**Comment by agostbiro** [comment]
Thanks for the quick reply! I've added the follow up issue here: https://github.com/RustCrypto/elliptic-curves/issues/612
