### ISSUE TITLE
password-hash: unsafe salt API

### ISSUE THREAD

**Issue by joepie91** [RustCrypto/traits#1029]
It looks like argon2's [`hash_password`](https://docs.rs/argon2/latest/argon2/struct.Argon2.html#method.hash_password) takes any string slice as a salt parameter. This invites API misuse; particularly specifying static salts or attempting 'clever' salt generation methods that ultimately weaken the security of the hash.

From a safe API design perspective, ideally it shouldn't be required to specify a salt manually at all (this instead being an internal process to the library unless explicitly manually overridden), but at the very least it should introduce an extra hurdle against misuse by requiring the user to pass in a `Salt` struct instead of a plain string slice - which `hash_password_customized` *does* do, so I'm not sure why this method doesn't.

**Comment by tarcieri** [comment]
Moved this issue to the `traits` repo as it's actually a concern with the [`password_hash::PasswordHasher`](https://docs.rs/password-hash/0.4.1/password_hash/trait.PasswordHasher.html) API.

De facto this API requires a B64-encoded [`Salt`] as that's what's required by the [PHC string format](https://github.com/P-H-C/phc-string-format/blob/master/phc-sf-spec.md). But notably there's a discrepancy between `PasswordHasher::hash_password` and [`PasswordHasher::hash_password_customized`](https://docs.rs/password-hash/0.4.1/password_hash/trait.PasswordHasher.html#tymethod.hash_password_customized), which takes an `impl Into<Salt>` as a parameter.

So, at worst, this API will return an error in the event the salt is not valid B64, so the real "safety" concern is more a type safety concern around the salt always being valid B64.

Perhaps `PasswordHasher::hash_password` should take `Salt` something convertible to a `Salt`.

**Comment by joepie91** [comment]
> Moved this issue to the `traits` repo as it's actually a concern with the [`password_hash::PasswordHasher`](https://docs.rs/password-hash/0.4.1/password_hash/trait.PasswordHasher.html) API.

Aha, I was unaware of this. Thanks.

> So, at worst, this API will return an error in the event the salt is not valid B64, so the real "safety" concern is more a type safety concern around the salt always being valid B64.

Okay, that does indeed alleviate the issue. I was going off the type signatures here, which suggested it would take any string - I'm generally used to strings-with-specific-constraints being encapsulated into their own types via a conversion method (which `Salt` does seem to do!), hence the confusion.

> Perhaps `PasswordHasher::hash_password` should take `Salt` something convertible to a `Salt`.

Assuming you meant "instead of something convertible [...]" there, I agree that that would be an improvement.

> This is a bit of a different question and more of a request for a new feature: support for randomly generating salts rather than taking them as a parameter. It's also tricky given the profiles this crate aims to support, including heapless targets that don't necessarily have a system RNG. Perhaps it'd be worth opening a separate issue?

My initial gut feeling would be to distinguish between the common case and the uncommon cases here - for example, strictly treating `hash_password` as a high-level function for the common case, including automatic internal salt generation, and simply making it unavailable in `no_std` environments entirely. Then `hash_password_customized` (or some other function that is clearly lower-level) could be used for `no_std` environments and other uncommon usecases alike.

I'll leave it up to you whether to split that out into its own issue - but I imagine that implementation-wise it'd overlap with the issue of "having a safe salt API", to such a degree that eg. simply removing the salt parameter from `hash_password` would resolve both concerns at once (since the `hash_password_customized` API is *already* safe in its salt handling).
