### ISSUE TITLE
digest: `Mac::new` is ambiguous with `KeyInit::new`

### ISSUE THREAD

**Issue by tarcieri** [RustCrypto/traits#1063]
In upgrading many projects, I frequently ran into the following:

```
error[E0034]: multiple applicable items in scope
    |         let mut mac = Aes128Cmac::new_from_slice(&key)?;
    |                                   ^^^^^^^^^^^^^^ multiple `new_from_slice` found
    |
    = note: candidate #1 is defined in an impl of the trait `KeyInit` for the type `CoreWrapper<T>`
    = note: candidate #2 is defined in an impl of the trait `digest::Mac` for the type `T`
```

To make this work I had to explicitly disambiguate all of these cases e.g. `<Aes128Cmac as Mac>::new_from_slice(...)`, but really one just calls the other so this feels like pointless makework/boilerplate.

In the next breaking change, I'd suggest getting rid of `Mac::new*` and using `KeyInit` instead.

**Comment by newpavlov** [comment]
The idea was that users should import either `Mac`, or a collection of the lower-level traits. But I agree that the collisions are quite annoying. Ideally we would use inherent traits without duplicating methods in convenience traits, but alas...

**Comment by tarcieri** [comment]
Dup of #1027
