### ISSUE TITLE
Provide `to_sec1_bytes` for `PublicKey`

### ISSUE THREAD

**Issue by KizzyCode** [RustCrypto/traits#1101]
Is there a reason why there is no `to_sec1_bytes`-method?

To parse a SEC 1 representation, we have `PublicKey::from_sec1_bytes` – however to serialize into a SEC 1 representation we need to detour via `EncodedPoint::from(&public_key)` and then use `encoded_point.as_bytes()`. Once you know this, it is pretty trivial – however it took me a few minutes to get there and its not that obvious IMO.

**Comment by tarcieri** [comment]
A PR to add such a method would be accepted.

It would need to be gated on the `alloc` feature, and could call `EncodedPoint::to_bytes`.
