### ISSUE TITLE
signature: Keypair not usable for keys not implementing the Signer trait

### ISSUE THREAD

**Issue by lumag** [RustCrypto/traits#1106]
The `Keypair` trait not usable for keys not implementing the `Signer` trait. For example, I looked upon implementing it for the new RSA key structures. Implementing the `Keypair` for the `pkcs1v15::SigningKey` involves some pain, put should be possible. For the `pss::SigningKey` the `Keypair` can not be implemented at all, since the PSS keys only implement the `RandomizedSigner` and `RandomizedVerified` traits.

**Comment by tarcieri** [comment]
Yeah, this is an unfortunate drawback of the current design.

It might make sense to have a different trait for associating a verifying key with a type which isn't prescriptive about how what signing operations it supports.

**Comment by lumag** [comment]
Yes, I'm going to look onto implementing `AsRef` for now.

**Comment by tarcieri** [comment]
The `Keypair` trait is not yet in widespread use so there is some opportunity to redesign it and deprecate it in its current form if the design is problematic

**Comment by lumag** [comment]
@tarciery What about removing the boundaries of `+Signer<S>` and `Verifier<S>`? I think it would be enough.

**Comment by lumag** [comment]
@tarcieri Another option might be to add `DigestKeyPair`, `RandomizedKeyPair`, etc, but I think this is a can of worms.

**Comment by lumag** [comment]
#1107
