### ISSUE TITLE
MSRV on `digest` v0.10.4 is broken

### ISSUE THREAD

**Issue by striezel** [RustCrypto/traits#1116]
When trying to build a project that depends on `digest` v0.10.4 with rustc 1.48, one gets error messages from cargo. This appears to be a similar issue like e. g. <https://github.com/RustCrypto/hashes/issues/398> and probably needs a similar fix like <https://github.com/RustCrypto/hashes/pull/401>.

The error message is:
```
error: failed to parse manifest at `/root/.cargo/registry/src/github.com-1ecc6299db9ec823/digest-0.10.4/Cargo.toml`

Caused by:
  feature `resolver` is required

  this Cargo does not support nightly features, but if you
  switch to nightly channel you can add
  `cargo-features = ["resolver"]` to enable this feature
```

The problem is due to the generated Cargo.toml containing the `resolver = "2"` line: https://docs.rs/crate/digest/0.10.4/source/Cargo.toml

Since the documented MSRV of `digest` is still rustc 1.41, this breaks the MSRV guarantee.

**Comment by newpavlov** [comment]
Argh... This error again. I will do release fix right away.

**Comment by newpavlov** [comment]
`digest v0.10.5` is published. Can you verify that it fixes the issue?

**Comment by striezel** [comment]
Yes, digest v0.10.5 can be compiled with rustc 1.48. So I consider this to be fixed.
