### ISSUE TITLE
Implement futures::AsyncWrite for hashers

### ISSUE THREAD

**Issue by piegamesde** [RustCrypto/traits#1129]
All hashers already implement `Write` which is great because it easily allows you to hash parts of your input:

```rust
std::io::copy(
  reader.take(n_bytes),
  hasher,
)?;
```

That same code does not work in an async context. Since the hashing code does not block, it should be easy to implement those traits behind a feature flag.

**Comment by newpavlov** [comment]
Honestly, the trait split introduced by the async system is annoying as hell. It's one of the reasons why I do not use Rust async, like at all. Regardless, while I do not plan to implement it myself,I am willing to accept a PR with such addition.

**Comment by piegamesde** [comment]
[`futures::io::AllowStdIo`](https://docs.rs/futures/latest/futures/io/struct.AllowStdIo.html) solves this.
