### ISSUE TITLE
Is there a way to get rid of getrandom?

### ISSUE THREAD

**Issue by domwoe** [RustCrypto/traits#1136]
I have the following dependencies in a project that needs to be compiled to wasm to run on the Internet Computer, i.e. not in the browser:

```
k256 = { version = "0.11", default-features = false, features = [
    "std",
    "ecdsa",
    "keccak256",
] }
```

Essentially, I need to verify a signature signed by a key corresponding to an Ethereum address.

When compiling to target `wasm32-unknown-unknown`, it fails with the following error:

```
error: the wasm32-unknown-unknown target is not supported by default, you may need to enable the "js" feature. For more information see: https://docs.rs/getrandom/#webassembly-support
   --> /Users/domwoe/.cargo/registry/src/github.com-1ecc6299db9ec823/getrandom-0.2.7/src/lib.rs:235:9
    |
235 | /         compile_error!("the wasm32-unknown-unknown target is not supported by \
236 | |                         default, you may need to enable the \"js\" feature. \
237 | |                         For more information see: \
238 | |                         https://docs.rs/getrandom/#webassembly-support");
    | |________________________________________________________________________^

error[E0433]: failed to resolve: use of undeclared crate or module `imp`
   --> /Users/domwoe/.cargo/registry/src/github.com-1ecc6299db9ec823/getrandom-0.2.7/src/lib.rs:262:5
    |
262 |     imp::getrandom_inner(dest)
    |     ^^^ use of undeclared crate or module `imp`

For more information about this error, try `rustc --explain E0433`.
```

`getrandom` is a dependency of `rand_core` which is used by a few dependencies related to the `ecdsa` feature.

Is there anything I can do?

**Comment by tarcieri** [comment]
You need to figure out what's enabling the `rand_core/getrandom` feature.

None of our crates do this by default. We have a separate `getrandom` feature in or crates which toggles this on (or in some legacy cases, the `std` feature enables it).

One of your non-RustCrypto dependencies is either enabling our `getrandom` feature, or directly enabling `rand_core/getrandom`.

**Comment by newpavlov** [comment]
IIUC `ecdsa` unconditionally [enables](https://github.com/RustCrypto/signatures/blob/master/ecdsa/Cargo.toml#L20) `rand_preview` for the `signature` crate.

**Comment by tarcieri** [comment]
@newpavlov the `signature` crate doesn't activate `getrandom` or provide any way to enable it at all:

https://github.com/RustCrypto/traits/blob/master/signature/Cargo.toml#L33

**Comment by newpavlov** [comment]
But then `std` in `k256` enables `elliptic-curve/std`, which then [enables](https://github.com/RustCrypto/traits/blob/master/elliptic-curve/Cargo.toml#L57) `rand_core/std`, which finally [enables](https://github.com/rust-random/rand/blob/master/rand_core/Cargo.toml#L27) `getrandom`.

**Comment by tarcieri** [comment]
Aah, yes. Unfortunate for WASM users.

@domwoe have you tried disabling the `std` feature of whatever dependency you're using directly?

**Comment by domwoe** [comment]
@newpavlov Good catch!

@tarcieri yep, It's a bit hacky at the moment but without the `std` feature I'm able to compile.

Thank you both!

**Comment by tarcieri** [comment]
It would be nice if `rand_core` let you enable `std` without enabling `getrandom`. For whatever reason they're coupled.

Hopefully moving the `Error` trait into core will eventually straighten this out, as I imagine that's what most people are after.

**Comment by newpavlov** [comment]
>For whatever reason they're coupled.

IIRC the problem was that it was impossible to enable `getrandom/std` conditionally on `rand_core/std` without bringing `getrandom` on board. Weak features were developed somewhat later after rand v0.8 was first released.

I would argue that the `wasm32-unknown-unknown` target is the weird one. It should not have been an `std` target, but convenience of having things like `HashMap` by default has won in the end...
