### ISSUE TITLE
digest: add `DynDigestWithOid`

### ISSUE THREAD

**Issue by tarcieri** [RustCrypto/traits#1182]
It'd be nice to have an object safe trait for obtaining the OID of a `DynDigest`. Something like:

```rust
pub trait DynDigestWithOid: DynDigest {
    fn oid(&self) -> ObjectIdentifier;
}
```

Separately that could probably use a trait like `DynAssociatedOid` in the `const_oid` crate, which ^^^ could be built on as a supertrait bound + blanket impl.

**Comment by newpavlov** [comment]
Could it work with `fn oid(&self) -> Option<ObjectIdentifier>` on `DynDigest` or do you need to enforce OID existence at compile time?

**Comment by tarcieri** [comment]
It would certainly be nice for it to work infallibly when needed
