### ISSUE TITLE
Want to contribute implementation of Vernam Cipher

### ISSUE THREAD

**Issue by Irene-123** [RustCrypto/traits#1184]
Hello there, I'm a student and learning rust everyday ^_^
I recently implemented vernam cipher in rust and want to contribute to my implementation if this is something that could be useful for this repository. This is my repo [link](https://github.com/Irene-123/Ciphers-in-Rust/tree/master/vernam_cipher), do let me know please. Thank you so much.

**Comment by newpavlov** [comment]
Naive one-time pad implementations are out of scope for this project.

**Comment by tarcieri** [comment]
A Vernam Cipher is closer to a stream cipher, but it falls under the category of "classical cryptography", where this project implements modern cryptography
