### ISSUE TITLE
signature 2.0 release seems to have broken ed25519 crate

### ISSUE THREAD

**Issue by DavidVorick** [RustCrypto/traits#1214]
I'm relatively new to rust so I apologize if I'm wrong about what's happening, but it appears to me that the release of Signature 2.0.0 is preventing ed25519 from compiling, with the following error message:

```
   Compiling ed25519 v1.5.2
error[E0405]: cannot find trait `Signature` in crate `signature`
   --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/ed25519-1.5.2/src/lib.rs:335:17
    |
335 | impl signature::Signature for Signature {
    |                 ^^^^^^^^^ not found in `signature`

For more information about this error, try `rustc --explain E0405`.
error: could not compile `ed25519` due to previous error
```

**Comment by DavidVorick** [comment]
Seems like the actual problem is with the ed25519 crate, I've filed an issue here: https://github.com/RustCrypto/signatures/issues/615

**Comment by tarcieri** [comment]
The issue is with the `ed25519` crate, not the `signature` crate
