### ISSUE TITLE
elliptic-curve/std doesn’t activate pkcs8/std

### ISSUE THREAD

**Issue by codahale** [RustCrypto/traits#1262]
My project has `p256` as a dependency with `std` enabled, but `EncodePublicKey::to_public_key_der`’s return type (`pkcs8::spki::Result`) doesn’t play nice with `?` because `pkcs8::spki::error::Error` doesn’t implement `std::error::Error`.

`p256/std` activates `elliptic-curve/std`, `pkcs8/std` activates `spki/std`, but `elliptic-curve/std` doesn’t activate `pkcs8/std`.

I can work around it just fine by adding `spki` as a direct dependency, but I figured I’d mention this since weak dependency features seem on the menu given the MSRV.

**Comment by tarcieri** [comment]
Will be in the next release of `elliptic-curve`

**Comment by codahale** [comment]
Awesome, thank you.
