### ISSUE TITLE
Expose y-coordinate in AffineCoordinates too

### ISSUE THREAD

**Issue by ia0** [RustCrypto/traits#1307]
I'm not sure why `trait AffineCoordinates` doesn't also have an `fn y(&self) -> Self::FieldRepr` similarly as for the x-coordinate. In particular given that's how it is stored in `struct AffinePoint`.

Would it be possible to also add such a method? Possibly as a provided method (and computed from `x()` and `y_is_odd()`). The `AffinePoint` implementation may explicitly implement it to avoid round-tripping.

**Comment by tarcieri** [comment]
Dup of #1019
