### ISSUE TITLE
cipher: `BlockEncryptMut` constrained by `BlockSizeUser`

### ISSUE THREAD

**Issue by bkstein** [RustCrypto/traits#1322]
@tarcieri @baloo I started implementing a builder for CMS `EnvelopedData`, which uses encryption for `EncryptedContentInfo`.

I would like to implement a function, that returns an encryptor for symmetric encryption. The idea is, that a user chooses an algorithm at runtime and the library encrypts data with this algorithm:

```rust
// [dependencies]
// aes = "0.8.2"
// cbc = "0.1.2"
// cipher = "0.4.4"
// crypto = "0.5.0"
// crypto-common = { version = "0.1.6", features = ["getrandom"]}

use aes::{Aes128, Aes256};
use cipher::BlockEncryptMut;
use cipher::consts::U16;
use cipher::crypto_common::rand_core::{CryptoRng, OsRng, RngCore};
use crypto::common::KeyIvInit;

enum SymmetricEncryptionAlgorithm {
    Aes128Cbc,
    Aes256Cbc
}

fn get_encryptor(alg: SymmetricEncryptionAlgorithm) -> Box<dyn BlockEncryptMut>
{
    type Aes128CbcEnc = cbc::Encryptor<Aes128>;
    type Aes256CbcEnc = cbc::Encryptor<Aes256>;

    match alg {
        SymmetricEncryptionAlgorithm::Aes128Cbc => {
            let (key, iv) = Aes128CbcEnc::generate_key_iv(OsRng);
            let encryptor = Aes128CbcEnc::new(&key.into(), &iv.into());
            Box::new(encryptor)
        }
        SymmetricEncryptionAlgorithm::Aes256Cbc => {
            let (key, iv) = Aes256CbcEnc::generate_key_iv(OsRng);
            let encryptor = Aes128CbcEnc::new(&key.into(), &iv.into());
            Box::new(encryptor)
        }
    }
}
```

This does not work, as the block size (type) must be known at compile time:

```
error[E0191]: the value of the associated type `BlockSize` (from trait `BlockSizeUser`) must be specified
  --> src/encryptor.rs:19:64
   |
19 | fn get_encryptor(alg: SymmetricEncryptionAlgorithm) -> Box<dyn BlockEncryptMut>
   |                                                                ^^^^^^^^^^^^^^^ help: specify the associated type: `BlockEncryptMut<BlockSize = Type>`
```

Is this intended? How can I handle this limitation?

**Comment by newpavlov** [comment]
`BlockEncryptMut` is fundamentally not an object-safe trait. At the very least you would have to fix block size, as noted by the error message. But even if you'll do it, the methods still will not be object safe. The most practical solution for you right now would be to introduce your own object-safe trait and implement it generically for `T: BlockEncryptMut`.

**Comment by tarcieri** [comment]
`BlockEncryptMut` is probably not the right abstraction. What if you want to add AEAD modes in the future, for example?

Also why do you need to decouple the selection of the encryptor from when it's used? Can you just have a function that matches on the various enum variants and calls the appropriate method then and there?

**Comment by bkstein** [comment]
> `BlockEncryptMut` is fundamentally not an object-safe trait.

Thanks for the reply. Looks like I will have to learn about object safety. But after @tarcieri's answer, I think that `BlockEncryptMut` is not the correct trait anyway. We might need a wider support of encryption algorithms for CMS.

**Comment by bkstein** [comment]
> `BlockEncryptMut` is probably not the right abstraction. What if you want to add AEAD modes in the future, for example?
> 
> Also why do you need to decouple the selection of the encryptor from when it's used? Can you just have a function that matches on the various enum variants and calls the appropriate method then and there?

@tarcieri I also was not sure, if `BlockEncryptMut` is wide enough to support all algorithms required in the future (for creation of CMS `EnvelopedData`). I could not find an appropiate trait that provides an `encrypt()` function for all symmetric encryption algorithms. And even `BlockEncryptMut` is not one trait, in practice it's many traits due to the dependence on `BlockSizeUser` and its associated `BlockSize` type, right?
So it looks like the cipher crate deliberatly doesn't support what I tried to implement with my `get_encryptor()` function. I will follow your suggestion to encrypt data right after the encryptor was created. This will allow for better extensibility.
