### ISSUE TITLE
crypto: doc build for v0.5.0 has failed

### ISSUE THREAD

**Issue by newpavlov** [RustCrypto/traits#1328]
See the docs.rs build log: https://docs.rs/crate/crypto/0.5.0/builds/794883

**Comment by tarcieri** [comment]
Attempting to republish in #1329.

I believe this was due to a bug in `elliptic-curve` which has since been fixed.

**Comment by tarcieri** [comment]
It built! https://docs.rs/crypto/0.5.1/crypto/
