### ISSUE TITLE
 How can I found some example about usage of cipher?

### ISSUE THREAD

**Issue by water-in-stone** [RustCrypto/traits#1338]

**Comment by newpavlov** [comment]
Implementation crates usually contain some usage examples, for example: [`aes-gcm`](https://docs.rs/aes-gcm/), [`chacha20poly1305`](https://docs.rs/chacha20poly1305/), [`chacha20`](https://docs.rs/chacha20/), [`cbc`](https://docs.rs/cbc/), [`ctr`](https://docs.rs/ctr/), [`aes`](https://docs.rs/aes/).

**Comment by tarcieri** [comment]
Maybe we should link to those crates as examples?

**Comment by newpavlov** [comment]
Ideally, we should include code examples in the trait crates proper, but there is the issue with circular dependencies.

Relevant issue: #1110
