### ISSUE TITLE
`set_pos_unchecked` should be an `unsafe fn`

### ISSUE THREAD

**Issue by joshlf** [RustCrypto/traits#1342]
https://github.com/RustCrypto/traits/blob/59490b50e88c252d179087072c1559303f8c5872/cipher/src/stream_wrapper.rs#L65-L68

`self.pos` has a safety invariant that `self.pos < T::BlockSize::USIZE`, so `set_pos_unchecked` should be an `unsafe fn`. There is currently no unsoundness - in practice, all calls to `set_pos_unchecked` are sound. This was discovered while [reviewing cipher for  vendoring in Fuchsia](https://fuchsia-review.googlesource.com/c/fuchsia/+/711365/9..13/third_party/rust_crates/vendor/cipher/src/stream_wrapper.rs#b65).

cc @anp

**Comment by newpavlov** [comment]
[According](https://doc.rust-lang.org/nomicon/working-with-unsafe.html) to the Rustonomicon safety works on module boundaries:

>The existence of make_room is not a problem for the soundness of Vec because we didn't mark it as public. Only the module that defines this function can call it. Also, make_room directly accesses the private fields of Vec, so it can only be written in the same module as Vec.

So the quoted code has no issues in this regard.

**Comment by joshlf** [comment]
Agreed, it's just that it makes approving code like this risky for us as outside reviewers going forward. We tend to focus most of our scrutiny on unsafe code, and so it'd be easy for us to miss if a new call to this function were added in a future version (even inside the module) since it wouldn't require an `unsafe` block. This is just a nice-to-have, not a soundness hole or anything that drastic.

**Comment by newpavlov** [comment]
I see your point. I am fine with marking it `unsafe`, so be free to submit a PR.
