### ISSUE TITLE
Access and serizalize inner state for Digest

### ISSUE THREAD

**Issue by ikrivosheev** [RustCrypto/traits#1579]
Hello! Thank you for the great library. I'll to describe what my issue. 

Pipeline of work with file is:

1. Create file with state
2. Upload chunk of bytes <-- it can call multiple time.
3. Finalize

State's shared between different process and different requests. I need to store hash inner state into database and then restore it in another process.

I can use this API: [decompose](https://docs.rs/digest/0.10.7/digest/core_api/struct.CoreWrapper.html#method.decompose). But don't have API to get [Sha256VarCore](https://docs.rs/sha2/latest/sha2/struct.Sha256VarCore.html) from [CtVariableCoreWrapper](https://docs.rs/digest/0.10.7/digest/core_api/struct.CtVariableCoreWrapper.html) and **Sha256VarCore** cannot serialize into bytes. 

Simple code:

```rust
let mut sha = Sha256::new();
sha2.update(bytes);
let (core, buffer) = sha.decompose();
// Store core and buffer into database
```

In other process after some time:
```rust 
// load core and buffer from database
let mut sha = Sha256::from_core(core);
sha.update(buffer.get_data());
sha.update(data);
```

**Comment by ikrivosheev** [comment]
If we come to a solution, I will be happy to make PR.

**Comment by tarcieri** [comment]
Dup of #1369.

This is already supported in the latest `sha2` master via the `SerializableState` trait: https://github.com/RustCrypto/hashes/blob/0b79171da599c1bd1b9d4bd45f537f217a2375df/sha2/src/core_api.rs#L104-L132

There's not a whole lot in the way of documentation around it though, and I'm not sure it's actually made it into a crate release yet.
