### ISSUE TITLE
cipher: Suspected typo in decrypt_padded documentation

### ISSUE THREAD

**Issue by tannaurus** [RustCrypto/traits#1586]
`BlockCipherDecrypt`'s `decrypt_padded` [method's documentation reads](https://github.com/RustCrypto/traits/blob/d15d165017c3b95c3c0263e9093948196863a1a5/cipher/src/block.rs#L261):

> Decrypt input and unpad it in-place. Returns resulting ciphertext slice.

But it is actually returning a slice of plaintext bytes. I suppose it would be fair to say "it's a slice of decrypted bytes that were written into the provided ciphertext buffer" but in it's current state, the documentation feels misleading/inaccurate (depending on how you look at it 😄 )

**Comment by newpavlov** [comment]
Yes, it should be "resulting plaintext slice".

**Comment by newpavlov** [comment]
Thank you for reporting this! Unfortunately, the fix will probably land only in the next breaking release (i.e. cipher v0.5), it will be somewhat inconvenient to to a backport for cipher v0.4.

**Comment by tannaurus** [comment]
No worries! Just confirming this is expected behavior is good enough for us 😃  thanks for the quick reply @newpavlov !
