### ISSUE TITLE
Can the elliptic-curve `hazmat` feature be removed?

### ISSUE THREAD

**Issue by mgeisler** [RustCrypto/traits#1597]
Hi there,

While vendoring this code, an internal reviewer asked me about the use of the `hazmat` feature in elliptic-curve: it looks [unused](https://github.com/search?q=repo%3ARustCrypto%2Ftraits+path%3A%2F%5Eelliptic-curve%5C%2F%2F+hazmat&type=code).

Would it make sense to remove it, or do you have it for consistency with the other crates?

**Comment by tarcieri** [comment]
I believe you're correct. It previously gated a small amount of functionality only intended to be used by implementations of elliptic curves, but those have since been removed.

**Comment by mgeisler** [comment]
Alright! I crated #1599 for this. It will be a breaking change, but maybe that's okay since the crate is at version 0.14.0 right now.
