### ISSUE TITLE
Add a hexdigest function

### ISSUE THREAD

**Issue by konstin** [RustCrypto/traits#16]
It is very common to exchange hashes as hexdigest. Creating a hexdigest using `Digest` currently requires using `format!`, e.g. `format!("{:x}", Sha256::digest(data))`. It would therefore be very convenient to have a function `hexdigest()` besides `digest()`. [Python](https://docs.python.org/3/library/hashlib.html#hashlib.hash.hexdigest) and [ruby](https://ruby-doc.org/stdlib-2.4.0/libdoc/digest/rdoc/Digest/SHA1.html) do even have this function in their standard library.

**Comment by tarcieri** [comment]
I'm not sure this makes sense in the context of this crate. I think functionality in this crate should be kept to the absolute bare minimum needed to actually do cryptography, and concerns like serialization should be handled by higher level crates.

**Comment by newpavlov** [comment]
I am a bit torn on this, from one side we indeed want `digest` crate to be minimal and addition of hex methods will require 4 methods (`result_hex`, `result_hex_upper`, `digest_hex`, `digest_hex_upper` and this is only if we are talking about `Digest` trait), but from another side it certainly will be an ergonomic improvement and we already have some convenience methods like `digest_str` and `digest_reader`, as well as `Digest` trait itself. It could be a good addition behind `std` feature gate, but I am not yet sure how we want to proceed with it.

**Comment by tarcieri** [comment]
Concretely the difference we're talking about here is:

## External crate

```rust
extern crate hex;
extern crate sha2;

use sha2::{Sha256, Digest};

fn main() {
    println!("digest: {}", hex::encode(Sha256::digest(b"foobar")));
}
```

## Hexdigest

```rust
extern crate sha2;

use sha2::{Sha256, Digest};

fn main() {
    println!("digest: {}", Sha256::hexdigest(b"foobar")));
}
```

Is it really worth complicating the digest crate over this? I don't think it's really reducing that much complexity for the end user, while it definitely complicates the trait interface.

**Comment by konstin** [comment]
It's probably more reasonable to implement this in generic-array, so you can do something like `digest().hex()` and `digest().hex_upper()`. This could even reuse the formatter implementations in generic-array. I'll open an issue over there.

**Comment by newpavlov** [comment]
Note, that after introduction of const-generics we will migrate from `generic-array`, so even if thos methods will be added, it will be only a temporary solution. So it's probably indeed better to just use `hex` crate instead.
