### ISSUE TITLE
Update generic-array version to version 1

### ISSUE THREAD

**Issue by jpgoldberg** [RustCrypto/traits#1611]
I am guessing that there is a good reason why` crypto::common` is re-exporting version 0.14.7 of the generic-array package instead of version 1 or greater. But because I don't know what those good reasons are I am filing this issue.

Feel free to tell me (or point me to) those good reasons and close this issue if such reasons exist. Otherwise there are some features (e.g. zeroize) and some new `From` and `TryFrom` implementations that I would find convenient, and I really don't want to play mix and match with different versions of the generic-array package.

Updating to a more recent version of the typenum package is probably an automatic side-effect of upgrading generic-array version, but I note it anyway in case it does need special attention.

**Comment by newpavlov** [comment]
We are in the process of migrating to [`hybrid-array`](https://docs.rs/hybrid-array), so we do not have plans to migrate to `generic-array v1.0`.
