### ISSUE TITLE
`digest` crate README example has the wrong return type?

### ISSUE THREAD

**Issue by juliusl** [RustCrypto/traits#1648]
The first example in the README has this,

> Now you can write the following code:
> 
> ```rs
> use sha2::{Sha256, Digest};
> 
> let mut hasher = Sha256::new();
> let data = b"Hello world!";
> hasher.update(data);
> // `input` can be called repeatedly and is generic over `AsRef<[u8]>`
> hasher.update("String data");
> // Note that calling `finalize()` consumes hasher
> let hash = hasher.finalize();
> println!("Result: {:x}", hash);
> ```
> In this example hash has type [GenericArray<u8, U64>](https://docs.rs/generic-array), which is a generic alternative to [u8; 64].

Shouldn't it be `GenericArray<u8, U32>`? 

From https://docs.rs/sha2/0.10.8/sha2/type.Sha256.html:
>pub type Sha256 = [CoreWrapper](https://docs.rs/digest/0.10.7/x86_64-unknown-linux-gnu/digest/core_api/wrapper/struct.CoreWrapper.html)<[CtVariableCoreWrapper](https://docs.rs/digest/0.10.7/x86_64-unknown-linux-gnu/digest/core_api/ct_variable/struct.CtVariableCoreWrapper.html)<[Sha256VarCore](https://docs.rs/sha2/0.10.8/sha2/struct.Sha256VarCore.html), [U32](https://docs.rs/typenum/1.17.0/typenum/generated/consts/type.U32.html), OidSha256>>;

**Comment by tarcieri** [comment]
Yes, looks like the digest was changed from `Blake2b` to `Sha256`, but that section was not updated accordingly
