### ISSUE TITLE
Get hash function name from Boxed DynDigest

### ISSUE THREAD

**Issue by Fethbita** [RustCrypto/traits#1683]
When I have a `Box<dyn DynDigest>` value, I would like to also be able to get what kind of function this is (ideally its name), for example using `hasher.name_str()` or similar, however I haven't been able to figure out how to do that. I am using the [Generic code example](https://github.com/RustCrypto/hashes/tree/master?tab=readme-ov-file#generic-code) in the hashes repository.

```rust
use digest::DynDigest;

fn select_hasher(s: &str) -> Box<dyn DynDigest> {
    match s {
        "md5" => Box::new(md5::Md5::default()),
        "sha512" => Box::new(sha2::Sha512::default()),
        _ => unimplemented!("unsupported digest: {}", s),
    }
}

let mut hasher1 = select_hasher("md5");
let mut hasher2 = select_hasher("sha512");

// How to get back "md5" or "sha512" from hasher1 and hasher2
```

--
A bit of off topic reason for this issue: I would like to switch to using RustCrypto for most of my crypto needs and would like to stop using openssl. However, currently, for signature verification I still continue to use openssl because it can parse X509 certificate, get public key and verify a signature with that public key. All of this might be possible with RustCrypto as of today, but I am having issues with not having enough examples in RustCrypto documentation, that's why I want to keep openssl until I figure out how I can get rid of it.

**Comment by newpavlov** [comment]
Algorithms in X509 certificates are identified not by names, but by OIDs. We expose it by implementing the [`AssociatedOid`](https://docs.rs/const-oid/latest/const_oid/trait.AssociatedOid.html) trait (usually it's feature-gated behind an [`oid` crate feature](https://github.com/RustCrypto/hashes/blob/master/sha2/Cargo.toml#L34)). In the next breaking release we will have the [`DynDigestWithOid`](https://docs.rs/digest/0.11.0-pre.9/digest/trait.DynDigestWithOid.html) trait, which may fit your use-case. But for now I would recommend to your own object-safe trait tailored for your use-case blanket implemented for `T: Digest + AssociatedOid`.

P.S.: The [`x509-cert`](https://docs.rs/x509-cert) crate may be helpfull. It's fairly low-level, but should be a fine starting point.
