### ISSUE TITLE
Max Salt Length Issue?

### ISSUE THREAD

**Issue by Bug-Reaper** [RustCrypto/traits#1723]
I see we've capped the max salt length to 64 bytes.
https://github.com/RustCrypto/traits/blob/8bb338103292e9e709c9b45009c568ed9a6276f9/password-hash/src/salt.rs#L112

I am re-implementing an old argon2id hash implementation that used salt of length of ~410bytes. As far as I was aware there is no max-salt length for argon2id but perhaps I'm mistaken?

EDIT: Quick google search and it does [appear](https://docs.pingidentity.com/pingds/7.2/configref/objects-argon2-password-storage-scheme.html#argon2-salt-length) we should be able to use salts much larger than 64 bytes. Sorry if this is the wrong place to ask about this, new to rust and crates ecosystem.

**Comment by newpavlov** [comment]
This restriction applies only to the PHC format. You can call methods on the [`Argon2`](https://docs.rs/argon2/latest/argon2/struct.Argon2.html) struct directly, they accept salts with lengths of up to 0xFFFFFFFF bytes.

**Comment by tarcieri** [comment]
Yes, the cap in the PHC format is mandated by the spec, and as @newpavlov said, if you want to avoid that don't go through the PHC string format APIs.
