### ISSUE TITLE
Release digest update with updated generic-array

### ISSUE THREAD

**Issue by kpcyrd** [RustCrypto/traits#23]
Hello!

We ran into an issue with digest while packaging it for debian. It currently depends on generic-array 0.9. We already have generic-array 0.11.1 in debian, we're trying to avoid packaging outdated versions.

Any chance you could release a new version with the most recent generic-array?

Thank you!

**Comment by newpavlov** [comment]
Yes, I plan to do it in a near future, see #22. But note that it will be a breaking change (because `GenericArray` is used as part of public API), so downstream crates will have to be updated as well.

**Comment by kpcyrd** [comment]
Awesome, thanks for you fast reply! Closing in favor of #22 :)

**Comment by burdges** [comment]
Apologies, I've maybe asked this before but I've forgotten:  What purpose does generic array crate actually serve here over say an associated type with appropriate bounds from `core`?  There are constructions for which const dependent types yield generic forms, but I cannot recall anything for which the generic array crate does so.

**Comment by newpavlov** [comment]
Traits for arrays are implemented only up to 32 elements, which in our case gives 256 bits. We could implement our own traits for various sizes used in our crates, but I don't think that it's an elegant solution. In some rare cases we also need advanced capabilities provided by `typenum`. ([1](https://github.com/RustCrypto/hashes/blob/master/groestl/src/groestl.rs#L21), [2](https://github.com/RustCrypto/block-ciphers/pull/27/files#diff-20cca436ccb7388663c45905a36f92aaR13)) Plus I think using generic array and typenum yields an easier to understand API and it will be easier to migrate from to const generics when they will land.
