### ISSUE TITLE
digest_reader should probably ignore std::io::ErrorKind::Interrupted

### ISSUE THREAD

**Issue by mthiesen** [RustCrypto/traits#24]
The current implementation of `digest_reader` treats `std::io::ErrorKind::Interrupted` like any other error. I have the feeling that it should ignore this particular error and just retry the read operation. This is what [`std::io::copy`](https://doc.rust-lang.org/src/std/io/util.rs.html#48-68) does as well.

**Comment by newpavlov** [comment]
Hm, I think you are right. In v0.8 `digest_reader` is removed in favour of `io::Read` implementation by all implementations, but it's worth to fix it  either way.
