### ISSUE TITLE
aead: add FromBlockCipher trait?

### ISSUE THREAD

**Issue by newpavlov** [RustCrypto/traits#259]
Unfortunately we can't rely on `From<BlockCipher>`, see #217.

**Comment by tarcieri** [comment]
I'm not sure this trait is necessary/helpful as it seems `From` is sufficient to solve the problem of converting a cipher into an AEAD?

Here's an example from the `aes-gcm` crate:

https://github.com/RustCrypto/password-hashes/pull/122#issuecomment-771960484

**Comment by newpavlov** [comment]
It works only because you work with a concrete cipher type. If I remember correctly issue with the MAC trait, your code will not work with a GCM implementation generic over block cipher.
