### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by konstin** [RustCrypto/traits#26]
I tried to upgrade to 0.8 but failed because `digest_reader` is gone. A changelog would be really helpful for such cases.

**Comment by newpavlov** [comment]
Yes, sorry for that. I definitely should start keeping changelogs, but I didn't get to that yet.

Meanwhile, as you can see from the [readme](https://github.com/RustCrypto/hashes#hashing-readable-objects), `digest_reader` was removed in favor of `io::Write` implementation.

**Comment by newpavlov** [comment]
I think we can close this issue since all crates in this repository now have changelogs thanks to @tarcieri.
