### ISSUE TITLE
cipher: merge block-modes crate

### ISSUE THREAD

**Issue by newpavlov** [RustCrypto/traits#272]
@o-klp has kindly shared with us ownership of the `cipher` crate.

I think it could be reasonable to merge traits from the listed crates into a single crate, this would reduce size of dependency tree a bit in some cases and will allow us to naturally introduce a trait (and support types) covering all kinds of non-authenticating ciphers.

**Comment by tarcieri** [comment]
Thanks @o-klp!

I unified the `block-cipher` and `stream-cipher` crates into `cipher` in #337, and released the result as `cipher` v0.2.0 in #337.

I'll leave this issue open to track merging `block-modes` into `cipher`.
