### ISSUE TITLE
aead: do not enable alloc by default?

### ISSUE THREAD

**Issue by newpavlov** [RustCrypto/traits#273]
Right now only `aead` enables `alloc` by default, which forces implementation crates to use `default-features = false`. Removing a default feature is a breaking change, so it would have to be done in v0.4.

**Comment by tarcieri** [comment]
This seems like an artifact of when `alloc` was mandatory. I'd agree with disabling it per default.

(as it were, `signature` enables `std` by default as well, although fixing this is tracked in #237)

**Comment by tarcieri** [comment]
One important change we'd have to do along with this is very clearly document enabling the `alloc` feature to use the allocating APIs, which are prominently featured in each crate.
