### ISSUE TITLE
Getting the output size from a hash function is currently awkward / maybe impossible

### ISSUE THREAD

**Issue by zmanian** [RustCrypto/traits#3]
Implementing several cryptographic functions like HKDF on top of functions that implement Digest requires generically inspecting the output size of the hash function and then throwing a runtime error for instance if too much output is requested from the caller. 

There doesn't seem to be an attractive way to do this in current Digest trait. I've run into this before and ran into recently with @warner.

**Comment by warner** [comment]
I'm working on updating rust-hkdf to use the Digest trait (and RustCrypto in general), and I'm currently running into this problem in the part that checks whether you're asking HKDF for more bytes than it can return (it hashes a one-byte block number along with the secret material so it's limited to 255 blocks, or `255 * HASHLEN` bytes). My current unfortunate hack is to hash an empty string and then explicitly measure the length of the vector that comes back:

https://github.com/warner/rust-hkdf/blob/fdd4a7dcc177a48317783b0fb06791caa2b1e753/src/hkdf.rs#L45-L48

(I'm pretty new at Rust, my apologies if there's something obvious that I'm missing entirely)

**Comment by newpavlov** [comment]
If you have `D: Digest` bound, you can write the following code using [`Unsigned`](http://paholg.com/typenum/typenum/marker_traits/trait.Unsigned.html) trait:
```Rust
use generic_array::typenum::Unsigned;

let size_in_runtime = D::OutputSize::to_usize();
```

BTW I would be happy to see your HKDF implementation as Pull Request in the [password-hashing](https://github.com/RustCrypto/password-hashing) repository!

**Comment by newpavlov** [comment]
Looks like this issue is solved, so I'll close it.
