### ISSUE TITLE
Decouple creation of block ciphers from using them

### ISSUE THREAD

**Issue by jonas-schievink** [RustCrypto/traits#30]
In some situations, creating a hardware-backed cipher can not only fail, but can also be impossible because only the downstream application has enough knowledge about the system.

For example, the nRF51 ARM microcontroller I'm working with has a hardware AES implementation that doesn't use special instructions, but is a peripheral with memory-mapped registers. This means that only one instance of the AES engine can exist in the whole program, and there's no way to know if one already exists.

For this use case, a `BlockCipher` trait looking like this would be more suitable:

```rust
trait BlockCipher {
    type KeySize: ArrayLength<u8>;
    type BlockSize: ArrayLength<u8>;
    type ParBlocks: ArrayLength<GenericArray<u8, Self::BlockSize>>;

    fn encrypt_block(&self, block: &mut GenericArray<u8, Self::BlockSize>, key: &GenericArray<u8, Self::KeySize>);
    fn decrypt_block(&self, block: &mut GenericArray<u8, Self::BlockSize>, key: &GenericArray<u8, Self::KeySize>);
}
```

(the same changes would need to be made for the other methods)

Note that it provides no way of creating an instance of `Self`. If that's needed, another trait can be introduced, which could look like this:

```rust
trait NewBlockCipher: BlockCipher {
    fn new() -> Self;
}
```

...actually, this is just `Default` in a trench coat, so I don't think it's needed at all. Are there cases where the key *must* be available at construction instead of when en/decrypting blocks?

What do you think? Would this limit any existing use cases?

**Comment by newpavlov** [comment]
So If I understand [this](https://developer.nordicsemi.com/nRF5_SDK/nRF51_SDK_v8.x.x/doc/8.0.0/s110/html/a00756.html) correctly (I think you can built a similar functions), your code can look like this:
```rust
struct AesHW { key: [u8; 16] }

impl BlockCipher for AesHW {
    // associated types
    fn new(key: Key) -> Self {
        // call nrf_ecb_init or check if peripheral device was initialized
        // (e.g. via static flag)
        Self { key: transmute_copy(key) }
    }

    fn encrypt_block(&self, data: &mut Data) {
        nrf_ecb_set_key(self.key.as_ptr());
        let r = nrf_ecb_crypt(data.as_mut_ptr(), data.as_ptr());
        assert!(r, "encryption has failed")
    }
}
```

I wonder if calling `nrf_ecb_set_key` for each block will not be too costly. Also there is still theoretical possibility of race condition: after `nrf_ecb_set_key` someone can change the key before we'll call `nrf_ecb_crypt`.

**Comment by jonas-schievink** [comment]
Wow, thanks for the quick reply!

> Key expansion step is usually quite expensive for block ciphers (which motivates development of tweakable block ciphers), so passing key in encrypt_block will be very inefficient.

Ah, I see. I misunderstood how that works.

> You load keys and block to specified registers and then wait for an interrupt?

Yes, pretty much this. The hardware component implementing AES-ECB is pretty simple, you basically pass it a pointer to this structure and wait for it to trigger the `ENDECB` event:

```rust
struct AesParams {
  key: [u8; 16],
  cleartext: [u8; 16],
  ciphertext: [u8; 16],
}
```

Since you just pass the key and cleartext (without any buffer space for round keys), this likely means that the hardware engine always does a full key expansion for every operation. While it's technically possible to cache the expanded key data in registers invisible to the application, I highly doubt they're doing that. Note that this "dumb" engine is reused by the AES-CCM peripheral, which likely does one key expansion per stream de/encrypt operation instead of doing one per block.

These peripherals are designed to be easy to use and only need to achieve Bluetooth Low Energy data rates, so redundant key expansion might not be a problem.

You also have to make sure that nothing tries to use the peripheral while your code is. The people working on embedded Rust already have a way to pass ownership of individual registers and blocks of registers belonging to a peripheral, so the struct that would implement the `BlockCipher` trait would look somewhat like this:

```rust
struct Aes {
  registers: RegisterBlock,
  params: &'static mut AesParams,
}
```

Both the `RegisterBlock` and `AesParams` are provided by the caller (the `&'static mut` is needed because the `AesParams` must always be at a fixed location in memory).

> Can you have one single "owner" of those registers which will dispatch requests from implementers of BlockCipher trait?

Possibly, but then the `BlockCipher` implementors would still need to know how to talk to the dispatcher, and someone (likely still the application) would have to create that dispatcher before any encryption is attempted.

> I guess it makes sense to decouple creation of block cipher and core encryption/decryption methods. In fact in previous versions it was exactly like that, and later they were merged into one trait for convenience.

Ah, I see. Looks like `{New}StreamCipher` still works that way.

> But the bigger problem is that assumption that you can infallibly construct block cipher instance from a given key goes up to the higher-level crates. (e.g. you can't construct AES-CTR from existing AES instance) So I am not yet sure how solution should look.

I guess you could have `NewStreamCipher` take an already constructed cipher instead of having it create one from the passed `key`.

I see now that this would invole quite a lot of changes. If you don't think this makes sense, feel free to close this - I'm sure I'll do fine by defining my own set of traits.

**Comment by newpavlov** [comment]
I will probably reintroduce `NewBlockCIpher` in the next major version.

In your case I think the most optimal approach will be to create `AesEngine` on application initialization which will be accessible via `pub static mut AES_ENGINE: *mut AesEngine = ptr::null;`. (one creation of the engine you will replace null pointer) It will handle peripheral initialization and dispatching of encryption/decryption requests. 

Now `Aes128` will implement `BlockCIpher` trait, `Aes128::new` will check if `AES_ENGINE` is not null (panicking otherwise), and `Aes128::encrypt_block` will send `AesParams` request to `AesEngine` and will wait for reply. (though I am not completely sure how to organize blocking behaviour here)
