### ISSUE TITLE
Add FromBlockCipher trait to stream-cipher

### ISSUE THREAD

**Issue by newpavlov** [RustCrypto/traits#32]

**Comment by tarcieri** [comment]
Would this look something like...

```rust
pub trait FromBlockCipher<C>
where
    C: BlockCipher
{
    fn from_block_cipher(cipher: C) -> Self;
}
```

**Comment by newpavlov** [comment]
Yes, but with addition of nonce/IV argument. I wonder if can assume `nonce: GenericArray<u8, C::BlockSize>`.

**Comment by tarcieri** [comment]
I think you'd probably want an associated type in that case...

```rust
pub trait FromBlockCipher<C>
where
    C: BlockCipher
{
    type NonceSize: ArrayLength<u8>;
    fn from_block_cipher(cipher: C, nonce: &GenericArray<u8, Self::NonceSize>) -> Self;
}
```

**Comment by newpavlov** [comment]
Are there any examples of nonce not being equal to block size for stream ciphers constructed from block ciphers?

**Comment by tarcieri** [comment]
I believe if you did it that way, you could have a blanket impl of `NewStreamCipher` for `FromBlockCipher`

```rust
impl<B, C> NewStreamCipher for C
where
    B: BlockCipher + NewBlockCipher
    C: FromBlockCipher<B>
{
    fn new(key: &GenericArray<u8, B::KeySize>, nonce: &GenericArray<u8, C::NonceSize>) -> C {
        C::from_block_cipher(B::new(key), nonce)
    }
}

**Comment by tarcieri** [comment]
> Are there any examples of nonce not being equal to block size for stream ciphers constructed from block ciphers?

Not that I know of. If https://github.com/rust-lang/rust/issues/29661 were ever to land we could add a default...

**Comment by tarcieri** [comment]
I guess we can start with the nonce being `GenericArray<u8, B::BlockSize>` in the blanket impl above and then go from there in the event there's actually a case where it matters.

Perhaps by then we'll have default associated types and it wouldn't even be a breaking change to introduce.
