### ISSUE TITLE
cipher: stream cipher seeking by counter value

### ISSUE THREAD

**Issue by tarcieri** [RustCrypto/traits#336]
Seeking by a counter value (e.g. NIST SP800-38D) is an exceedingly common operation, whether a stream cipher is a block cipher in counter mode (e.g. AES-CTR), or if a stream cipher uses an underlying block-based construction (ChaCha20, Salsa20). As it were, such seeking is necessary to implement AES-GCM, ChaCha20Poly1305, and XSalsa20Poly1305.

The current [`SyncStreamCipherSeek`](https://docs.rs/stream-cipher/0.7.1/stream_cipher/trait.SyncStreamCipherSeek.html) trait provides the ability to seek anywhere in the keystream at a byte-level granularity. This complicates the internal buffering logic by requiring stream ciphers to work at non-block-oriented offsets.

I think it'd be nice to have a trait that just accepts a counter value, rather than one which specifies a [`SeekNum`](https://docs.rs/stream-cipher/0.7.1/stream_cipher/trait.SeekNum.html)-style byte offset. If we had such a trait, I think we could implement `SyncStreamCipherSeek`-like behavior in a single place, as opposed to the current state of affairs where internally the `chacha20` and `salsa20` crates contain copy-pasted code from `ctr::Ctr128`.

cc @newpavlov

**Comment by newpavlov** [comment]
Yes, it seems worth looking into providing more fundamental non-buffering primitives, on top of which will be constructed convenient buffering ones using a generic wrapper similar to [`BlockBuffer`](https://docs.rs/block-buffer/). It should also help with composability (e.g. we can share buffer between MAC function and stream cipher).

**Comment by newpavlov** [comment]
`cipher v0.4` now exposes the [`StreamCipherSeekCore`](https://docs.rs/cipher/0.4.2/cipher/trait.StreamCipherSeekCore.html) trait which should handle this issue.
