### ISSUE TITLE
blobby?

### ISSUE THREAD

**Issue by ignatenkobrain** [RustCrypto/traits#34]
I can't find github repo for blobby which is used by digest… Can you please create it and include LICENSE in it?

**Comment by tarcieri** [comment]
https://github.com/RustCrypto/utils/tree/master/blobby

It's dual licensed Apache2+MIT as noted in both Cargo.toml and the parent of the repo.

It does look like the link to the repo needs to be updated though:

https://github.com/RustCrypto/utils/blob/master/blobby/Cargo.toml#L8

**Comment by ignatenkobrain** [comment]
Then can you please ship licenses with tarball on crates.io? I've been filing those tickets some time ago and I think it's only one who doesn't ship license files.

**Comment by newpavlov** [comment]
Ah, indeed I've missed LISENSE files for `blobby` and `dbl` for some reason. Now it's fixed.

BTW have you seen [`cargo license`](https://github.com/onur/cargo-license)?

**Comment by ignatenkobrain** [comment]
@newpavlov nope, not yet ;)

Looks pretty nice, although it doesn't help with missing license file. Thanks for fix!
