### ISSUE TITLE
cipher: remove generic_array re-exports from `block` and `stream` modules

### ISSUE THREAD

**Issue by tarcieri** [RustCrypto/traits#344]
The `block` and `stream` modules of the `cipher` crate both re-export `generic_array` and `typenum::consts`.

A toplevel re-export was added after the publication of `cipher` v0.2 in #343.

Before publishing `cipher` v0.3, we should remove the re-exports from `block` and `stream` and require using the toplevel one instead.

**Comment by newpavlov** [comment]
Also it's probably worth to hide the `dev` module from the `block-cipher` module. Right now it only re-exports `blobby`, I think it can be re-exported at the top level of the `cipher` crate instead.

**Comment by tarcieri** [comment]
@newpavlov yeah, left some notes about `dev` module fixups in #342

**Comment by tarcieri** [comment]
The `block` and `stream` modules are no longer part of the public API at all, so I think it's safe to say this was addressed.
