### ISSUE TITLE
Release a 0.8.0 version?

### ISSUE THREAD

**Issue by hdevalence** [RustCrypto/traits#35]
Hi there, the current version of the crate in git is `0.8.0`, but this isn't published to crates.io yet. Would it be possible to release a `0.8.0` version, or are there other changes to be made first?

**Comment by newpavlov** [comment]
You mean `crypto-mac`, right? I was thinking about also bumping edition to 2018 and do the same for other crates. But i guess it will not be late to do it in `crypto-mac v0.9`, so I can publish `v0.8` today-tomorrow.

What is your policy regarding editions for `dalek` crates?

**Comment by hdevalence** [comment]
Cool! I don't think we have a policy, that could be good to think about.

**Comment by hdevalence** [comment]
Bump -- would it be possible to put out an `0.8.0` version?

**Comment by hdevalence** [comment]
Hi again, it would be great to be able to eventually deprecate subtle version `1.0` once its users have upgraded, so it would be great to have an updated `crypto-mac` crate release to allow people to start upgrading.

**Comment by AxelNennker** [comment]
May I kindly ask what is holding the publication of 0.8 back?

**Comment by tarcieri** [comment]
No one has done the upgrade / release work

**Comment by tarcieri** [comment]
This is tracked in #43. Expect a release later this week.

**Comment by tarcieri** [comment]
`cargo-mac` v0.8.0 has been released
