### ISSUE TITLE
Variable key length does not work with streamciphers

### ISSUE THREAD

**Issue by dignifiedquire** [RustCrypto/traits#36]
Given that the blockciphers specify a fixed key size, this check https://github.com/RustCrypto/traits/blob/master/stream-cipher/src/lib.rs#L42-L46 fails when trying to use a key of variable size. As far as I understand this should proxy through to the underlying [`new_varkey`] of the blockcipher instead

**Comment by newpavlov** [comment]
Stream cipher traits are not inherently connected to block ciphers, so idea was to ovewrite this method in block mode crates, but it seems I [forgot](https://github.com/RustCrypto/stream-ciphers/blob/master/ctr/src/lib.rs#L119) to do it.

**Comment by newpavlov** [comment]
Fixed in this [commit](https://github.com/RustCrypto/stream-ciphers/commit/d59145d8bb100bf077274bc5e5ae8155f2472e35).

**Comment by dignifiedquire** [comment]
thank you!
