### ISSUE TITLE
Add result method which gets signature without taking ownership

### ISSUE THREAD

**Issue by windelbouwman** [RustCrypto/traits#38]
The current `Digest::result` method takes ownership of the hasher. This prevents calling result multiple times and continue hashing. Is this on purpose? It would be good if the result method could be called repeatedly by passing in a reference.

**Comment by newpavlov** [comment]
You can use [`result_reset`](https://docs.rs/digest/0.8.0/digest/trait.Digest.html#tymethod.result_reset) method. (note: depending on the compiler smarteness it may produce not the best code right now, but it may be improved in future versions)

**Comment by windelbouwman** [comment]
Yes, I used this method, the problem is that I do not want the internal state to be reset. I worked around this by creating a wrapper which keeps the data in an array. This will be very inefficient off course.

https://github.com/RustPython/RustPython/pull/1064/files#diff-c381f8e770a8dec0b8d179cd9135d463R277

Sorry for not being too clear about the logic I need.

**Comment by newpavlov** [comment]
Wait, do you understand that during finalization the inner state of hash function changes? In other words, if result was hypothetically using `&mut self`:
```rust
let mut d = Sha256::new();
d.input(&msg1);
let _ = d.result();
d.input(&msg2);
let hash1 = d.result();
let msg3 = msg1.extend(&msg2);
lee hash2 = Sha256::digest(&msg3);
```
Here `hash1` will not be equal to `hash2`. I think you simply want to clone hash function state and store it for future use, before calling `result`.

**Comment by windelbouwman** [comment]
Ah, yes, that's what I want. I tried to clone the `DynDigest` trait, but could not figure it out. Is this possible? Given a `DynDigest` trait, clone it for continuation?

**Comment by newpavlov** [comment]
Ah, so you needed `DynDigest` cloning. See the linked PR.

**Comment by windelbouwman** [comment]
This works greatly! Thanks a bunch!

Still, maybe the get_result method can be change in not taking ownership of the hashing function. This is more in line with the legacy rust-crypto crate. This function would then internally clone the state, and yield the result from this cloned state.

**Comment by newpavlov** [comment]
It's done intentionally to prevent potential misuses, i.e. you should be explicit by using `result`, `result_reset` or `clone`, which I think is a more "Rusty" approach.

**Comment by tarcieri** [comment]
> This is more in line with the legacy rust-crypto crate.

That isn't a particularly good rationale.

> It's done intentionally to prevent potential misuses

👍

**Comment by windelbouwman** [comment]
Thank you for the explanation. I already suspected a reasoning which I was unaware of.
