### ISSUE TITLE
Docs provide little guidance that Digest is usually the best trait bound

### ISSUE THREAD

**Issue by zmanian** [RustCrypto/traits#4]
When implementing functions that operate generically over the Digest and related traits the current RustDocs provide little guidance that the trait bound you almost always want is `Digest` and not `Input + BlockInput + FixedOutput + Default`.

**Comment by mzabaluev** [comment]
I beg to differ: in generic code it makes sense to specify precisely which traits you need.
In client code that just wants to use a concrete digest implementation, the convenience trait `Digest` is usually the best indeed.

**Comment by newpavlov** [comment]
I've added a small note about `Digest` to `digest` crate. I think it should be enough. But feel free to send a PR if you'll have ideas on how to improve docs!
