### ISSUE TITLE
PublicKeys can be zero

### ISSUE THREAD

**Issue by rozbb** [RustCrypto/traits#415]
Re the recent changes, I tried this code in `p256` and it failed (i.e., it didn't panic)

```rust
#[should_panic]
#[test]
fn zero_pubkey() {
    PublicKey::from_sec1_bytes(&[0]).unwrap();
}
```

This is because `PublicKey::from_encoded_point` doesn't use the identity-sensitive `PublicKey::from_affine` method. I'm sending a PR right now to fix this

**Comment by tarcieri** [comment]
Thank you!
