### ISSUE TITLE
arr! cannot be imported with use syntax

### ISSUE THREAD

**Issue by lovasoa** [RustCrypto/traits#42]
The following does not work, and it is annoying when defining a static key and iv using rust 2018 : 

```rust
use block_cipher_trait::generic_array::arr;
let key = arr![u8; 91,99,219,17,59,122,243,224,177,67,85,86,200,249,83,12];
```

The problem has been [fixed](https://github.com/fizyk20/generic-array/commit/7c32c625e51aaf2c412f78871a173b7eb458e591) in `generic-array`, but `block_cipher_trait` still requires and re-exports an old version of `generic-array`.

It would be nice if the dependency could be bumped to the latest version, and a new version of this crate were published.

**Comment by newpavlov** [comment]
We plan to publish new versions (though no ETA yet) with a bumped `generic-array` version. Meanwhile you can write code like this:
```rust
// type inference usually will deduce a correct type
let key = [91,99,219,17,59,122,243,224,177,67,85,86,200,249,83,12].into();
```

**Comment by tarcieri** [comment]
Going to go ahead and close this out as all of the crates are now 2018 edition (on `master`, as `-pre` releases) and I confirmed this now works.
