### ISSUE TITLE
elliptic-curve (and others): JWK support

### ISSUE THREAD

**Issue by tarcieri** [RustCrypto/traits#446]
We received a request for JWK support in the `elliptic-curve` crate:

https://github.com/RustCrypto/signatures/issues/221

I think it'd be good to support JWK (as an optional feature) in the `elliptic-curve` crate, and possibly other crates e.g. `rsa`.

I think ideally we'd have some sort of `jwk` crate in the https://github.com/rustcrypto/utils repo, similar to the [`pkcs8`](https://github.com/RustCrypto/utils/tree/master/pkcs8) crate.

Unfortunately `jwk` is taken and not used for anything (one version published January 2016, yanked):

https://crates.io/crates/jwk/versions

Perhaps we could spike out JWK support in the `elliptic-curve` crate and then pick a name for a general-purpose JWK crate and then try to generalize it.

**Comment by newpavlov** [comment]
I have contacted the initial owner of the `jwt` crate (@esclear), but unfortunately he has already transferred ownership to another person. He has kindly provided a contact email of the new owner, so I contacted him, but unfortunately I did not receive any reply from him yet.

@esclear
Could you please ping the new owner in this thread? I couldn't find his GitHub nickname using the email address.

**Comment by tarcieri** [comment]
I also tried contacting the owner of the `jwk` crate a little over a week ago and haven't heard back.

**Comment by esclear** [comment]
According to [crates.io](https://crates.io/api/v1/crates/jwk/owner_user), the `jwt` crate is still owned by @JTKBowers.

**Comment by newpavlov** [comment]
@esclear 
Sorry, it was a typo on my side.

**Comment by tarcieri** [comment]
Absent a common crate for implementing JWK, I added an EC-specific JWK implementation to the `elliptic-curve` crate in https://github.com/RustCrypto/traits/pull/483
