### ISSUE TITLE
password-hash: MCF support

### ISSUE THREAD

**Issue by tarcieri** [RustCrypto/traits#450]
Now that #437 is landed, we should have fairly robust, generic support for the [PHC string format](https://github.com/P-H-C/phc-string-format/blob/master/phc-sf-spec.md).

However, the [Modular Crypt Format (MCF)](https://passlib.readthedocs.io/en/stable/modular_crypt_format.html) is much more common, albeit underspecified. While the PHC format makes more sense to focus on as a forward-thinking default, it would still be good to be able to parse and serialize MCF strings as well.

A couple options:

1. Have separate `PhcHash` and `McfHash` types.
2. Make `PasswordHash` capable of representing the PHC or MCF formats.

I think regardless of either of these approaches, we should treat them separately, which is to say that there should at least be separate methods for working with MCF hashes (if not types).

Beyond that, the main distinctions between the two seem to be laxer rules for MCF (e.g. it can have a trailing `$` on the end which is ignored), and how the "params" are parsed.

Namely, MCF hashes often accept a single, unlabeled parameter as the second segment. Here's an example using bcrypt:

```
$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy
\__/\/ \____________________/\_____________________________/
 Alg Cost      Salt                        Hash
```

Note the `$10` "cost" parameter.

That can be parsed easily enough as a `Value`, which means we could change `PasswordHash` to have a `params` field something like:

```rust
pub enum Params {
    Phc(PhcParams),
    Mcf(Value)
}
```

This would disambiguate between PHC and MCF hashes and allow supporting both formats without too much work.

**Comment by tarcieri** [comment]
To make things even trickier, it seems that the reference implementation of Argon2 now produces hashes like the following:

https://github.com/P-H-C/phc-string-format/issues/1

```
$argon2i$v=19$m=512,t=2,p=2$5VtWOO3cGWYQHEMaYGbsfQ$AcmqasQgW/wI6wAHAMk4aQ
```

Note the `$v=19` parameters separate from the `$m=512,t=2,p=2`

**Comment by tarcieri** [comment]
Another thing to consider are salts. The implementation in #437 always attempted to encode/decode them as B64, however re-reading the [PHC spec](https://github.com/P-H-C/phc-string-format/blob/master/phc-sf-spec.md), it says:

> The salt consists in a sequence of characters in: `[a-zA-Z0-9/+.-]` (lowercase letters, uppercase letters, digits, `/`, `+`, `.` and `-`). The function specification MUST define the set of valid salt values and a maximum length for this field. Functions that work over arbitrary binary salts SHOULD define that field to be the B64 encoding for a binary value whose length falls in a defined range or set of ranges.

So regardless of anything else, the implementation should be updated to not eagerly parse salts as B64 (and as it were, those rules are already captured by the `ValueStr` type).

Beyond that, the PHC spec mandates a minimum length for a salt, whereas MCF is the wild west.

**Comment by tarcieri** [comment]
Thinking about this a little more, and given the additional complexity of a version field in the PHC format, I'm thinking it might be best to make `PasswordHash` an enum with `PasswordHash::Phc` and `PasswordHash::Mcf` variants, with methods for the fields they have in common.

**Comment by tarcieri** [comment]
After poking at MCF a little more, it doesn't look like my "methods for the fields they have in common" idea will work out.

Going back to the example above:

```
$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy
\__/\/ \____________________/\_____________________________/
 Alg Cost      Salt                        Hash
```

There is no delimiter for the salt versus the hash.

Furthermore, we can't even rely on the encoding being "B64". Here's another bcrypt MCF hash:

```
$2b$10$3euPcmQFCiblsZeEu5s7p.9OVHgeHWFDk9nhMqZ0m/3pd/lhwZgES
```

Note the `.` character. It seems bcrypt MCF hashes define their own completely nonstandard Base64 encoding where instead of the 62nd and 63rd characters mapping to symbols, the *first* and *second* characters map to `.` and `/` respectively (confusingly this encoding appears to be referred to as "B64" sometimes, but it's notably different from the PHC "B64" encoding, which omits `=` characters).

So really there's very little we can do generically with MCF hashes besides potentially parse the prefix. Everything else is algorithm-specific.

We could potentially add some traits for algorithm-specific handling of raw MCF strings, and/or a way to use an algorithm-specific method to "upgrade" an MCF hash to a PHC hash. But beyond that, MCF is an ill-specified, de facto scheme which seems to deliberately resist abstractions.

**Comment by tarcieri** [comment]
I opened #450 which provides the most flexible, minimalist take I could think of, which is a trait for upgrading MCF hashes to PHC hashes, and a default method which can run that method on the fly and verify the resulting PHC hashes.

**Comment by ibotty** [comment]
Beating a dead horse, how is e.g. bcrypt to implement `McfHasher`?  Should it make up its PHC format?  And given that it uses this strange b64 encoding, should it re-encode using the standard encoding?

**Comment by tarcieri** [comment]
@ibotty whenever possible I'd suggest using existing precedent for the PHC serialization for existing algorithms in order to promote interoperability.

Here is an existing one for bcrypt:

https://github.com/simonepri/phc-bcrypt

Example:

```
$bcrypt$v=98$r=10$Fu+++1sHIGTodjyG4pF4Sw$QlOihTVOARhpV0EiWv4k10i5Pw5Hm0E
```

This uses a `$bcrypt` previx, the `$v` version parameter, cost is `$r=`, and it uses standard Base64.

> And given that it uses this strange b64 encoding, should it re-encode using the standard encoding?

The MCF format for bcrypt uses a special encoding. FWIW, that's implemented by the `base64ct` crate, and thus `password-hash`:

https://docs.rs/password-hash/latest/password_hash/enum.Encoding.html#variant.Bcrypt

However, PHC hashes should always use the standard "B64" encoding.

**Comment by ibotty** [comment]
I also found that encoding.  I'll check whether it really uses the standard base64 encoding.
