### ISSUE TITLE
aead: Should we have StatefulAead rather than StatelessAead?

### ISSUE THREAD

**Issue by tarcieri** [RustCrypto/traits#46]
Right now we have a stateful `Aead` trait and a `StatelessAead` trait.

It seems like the common case for anything based on a stream cipher (pretty much all AEADs) is `StatelessAead`, and that `StatelessAead` is more useful in that it's `Send` + `Sync`.

Should we rename `StatelessAead` to `Aead`, and rename the current `Aead` trait to `StatefulAead` instead? I think this follows the general Rust convention of giving the immutable version of something the shorter, more convenient name.

**Comment by burdges** [comment]
All AEADs that require randomness count as stateful, right?

Is there much cryptographic reason for users to restrict to stateless?  If yes, then maybe saying stateless better indicates that restriction?  If no, then even `AeadMut` vs `Aead` maybe better indicates the statefulness as being a code restriction.  

I think stateful AEAD types are often `Send + Sync` themselves, but you cannot invoke the stateful AEAD methods.  If they've some `R: RngCore` paramater then `R = &mut ..` makes them not `Sync` and `R = ThreadRng` makes them not `Send`.
