### ISSUE TITLE
*::new to should return Result<T, E>

### ISSUE THREAD

**Issue by benpye** [RustCrypto/traits#47]
I believe that our `*::new` methods should return `Result<T, E>`. I say this because many existing crypto implementations may fail unexpectedly on initialization. Currently wrapping these libraries and implementing the RustCrypto traits necessitates the use of `panic!` or similar to ensure that the program is aborted when the init fails - this is clearly not desirable. Whilst in some cases we may be able to determine at compile time (and ensure via types) that it will not fail - I am not convinced that failures can always be avoided - for example mismatched dependencies.

**Comment by newpavlov** [comment]
Except sizes and algorithm ID mismatches what are common failure modes in your opinion? Although having `Result` methods may be useful either way for algorithms running on an external hardware. But I think a better approach will be to introduce `try_new` methods. Also do you mean all traits (including things like hashes)?

I will include your proposal to the issue which discusses next versions of crates.

**Comment by burdges** [comment]
What should `E` be when doing `try_new`?

**Comment by tarcieri** [comment]
@burdges if there's a trait crate that doesn't already have an (opaque) error type, I'd say go ahead and add one, ala:

https://docs.rs/aead/latest/aead/struct.Error.html

**Comment by tarcieri** [comment]
Hrmm, so the odd thing about the external cryptographic hardware case is it's not compatible with the existing `new` method, as that takes the key and the point of using external hardware is to store the key there.

On a separate note, it'd probably make sense to split all of the `new` methods into `New*` traits (which we have several places, but not in `crypto-mac` for example) so hardware devices don't have to impl them.

**Comment by tarcieri** [comment]
Going to close this out. Please reopen if there is a valid use case for this.
