### ISSUE TITLE
Use const generics

### ISSUE THREAD

**Issue by burdges** [RustCrypto/traits#517]
We've [min_const_generics](https://github.com/rust-lang/rust/pull/79135) approaching some stable release, which should suffice for replacing generic arrays everywhere.  

Apologies if this came up elsewhere, not too plugged into these crates lately.

**Comment by newpavlov** [comment]
As written [here](https://github.com/RustCrypto/traits/issues/238#issuecomment-666187297) `min_const_generics` are not sufficient for our needs. We also probably will need for rust-lang/rust#76560 to be resolved and stabilized as well (hopefully in a different form from the approach which the feature uses now).

**Comment by burdges** [comment]
I'll close this in favor of https://github.com/RustCrypto/traits/issues/238 then

**Comment by tarcieri** [comment]
We need `min_const_generics` + traits (i.e. using an associated constant as a const generic), so unfortunately the former alone is insufficient for our use cases.

There are a few places where we could consider const generics immediately. Namely in the `der` crate I use `typenum` (sans `generic-array`) to control the size of `BigUint`, but offhand that's really the only one I can think of where they're immediately applicable.
