### ISSUE TITLE
Crate for common traits?

### ISSUE THREAD

**Issue by newpavlov** [RustCrypto/traits#536]
For a long time I thought about creating a crate with some common traits shared by several algorithm families. Here is a rough list of traits which could be defined in it:
- `FromKey`: replaces `NewAead`, `NewMac`, `NewUniversalHash`, `NewBlockCipher`.
- `FromKeyNonce`: replaces `NewCipher`. Could be used for AEAD?
- `Update`/`UpdateCore`: replaces `digest::Update/UpdateCore`, partially `Mac` and `UniversalHash`.
- `Reset`: replaces `digest::Reset`, partially `Mac` and `UniversalHash`. Also can be a potential shortcut for `StreamCipherSeek::seek(0)`.
- `FinalizeFixed`: replaces `digest::FixedOutput`, partially `Mac` and `UniversalHash`. `Mac` and `UniversalHash` will be extension traits for `FinalizeFixed` with additional family-specific helper methods.

Higher level crates will simply re-import required traits, so existence of this crate should be almost invisible for users.

Addition of such crate will help reduce a bit the total amount of traits which we define. The main motivation for introducing it now is trait interactions in `blake2`. The main disadvantage of this approach is that we add yet another crate to our already somewhat complex crate hierarchy. Also even though the proposed traits are quite simple and probably will be rarely changed, breaking change in this crate will ripple through downstream trait crates.

**Comment by tarcieri** [comment]
Perhaps `crypto-common`?

I agree it would be nice to have such a crate.

**Comment by newpavlov** [comment]
Yeah, I had exactly the same name in mind. :)
