### ISSUE TITLE
Prefer `&mut [u8]` over returning a newly allocated `Vec<u8>`; derive the latter from the former

### ISSUE THREAD

**Issue by WildCryptoFox** [RustCrypto/traits#56]
`#[no_std]` is already common between these crates but when they pull in alloc for Vec, and always allocate, you lose the ability to reuse allocations between calls.

At least an `_in_place`.

**Comment by newpavlov** [comment]
Are you talking about the `aead` crate? We had a very lengthy [discussion](https://github.com/RustCrypto/traits/pull/40) about non-allocating API. So we decided to start with a simple non-controversial allocating API and add non-allocating methods later.

**Comment by james-darkfox** [comment]
@newpavlov I am, though I didn't want to discriminate against other cases where it may apply too. Thanks for the link. Later is fine.

**Comment by tarcieri** [comment]
I've been meaning to submit a follow-up PR with my thoughts as I'd like to address the in-place API before moving Miscreant over to the traits in the `aead` crate

**Comment by tarcieri** [comment]
We added in-place APIs to the `aead` crate in #58 and #59
