### ISSUE TITLE
Unexpected assertion failure on SecretKey::from_bytes

### ISSUE THREAD

**Issue by Splamy** [RustCrypto/traits#588]
I don't know if this is intended or not, but when passing a slice to `p256::SecretKey::from_bytes(bytes)` which is not the correct size (in the p256 case here 32 bytes), the call will panic due to a failed assertion in `GenericArray`.
Since the function returns a `Result` I kinda would expect it to return an error instead.

The underlying problem is that the method `from_bytes` indeed tries to call `try_into` [here](https://github.com/RustCrypto/traits/blob/master/elliptic-curve/src/secret_key.rs#L108) but `GenericArray` does not implement `TryInto` but only `Into` with a length assertion beforehand ([see here](https://github.com/fizyk20/generic-array/blob/master/src/lib.rs#L553-L563)).

The quick fix here would be to add a length check before the `try_into`
I think the general problem lies with the `GenericArray` crate which should have implemented TryFrom instead, but that seems like a desing choice of that crate, idk.

**Comment by tarcieri** [comment]
Indeed that looks problematic, and makes me wonder where else this might be happening.
