### ISSUE TITLE
Test GitHub Actions for CI

### ISSUE THREAD

**Issue by akhilles** [RustCrypto/traits#60]
I noticed a bit of wonkiness in the current CI setup for this project. This seems to be due to the use of Cargo workspaces, which has terrible interactions with features. Can we try separate builds for each crate in a repo? I think there are a bunch of benefits to this:

- Provides more flexibility for testing the individual crates since the complexity associated with multiple features and/or targets won't pollute the entire repository.
- Allows for separate MSRV for each crate.
- Might help with PRs such as https://github.com/RustCrypto/hashes/pull/85 getting merged sooner.

Travis CI is probably not suitable for this since it'll lead to one large `.travis.yml` file with a lot of conditionals and environment variables. With GitHub Actions, you can have multiple workflows in each repo that can be triggered based on path-based filtering. So, a PR that modifies `md5` wouldn't trigger the `sha2` workflow. Also, each workflow file can reside in its respective subdirectory.

Would be great if we could do a trial run of GitHub Actions on the `traits` repo (without removing Travis builds).

**Comment by tarcieri** [comment]
I'd be a fan of migrating to GitHub Actions. I use it on several other projects and generally find it faster with better UX than Travis CI.

The only downside is the lack of caching, but I hear that will be fixed soon.

**Comment by akhilles** [comment]
Looks like GitHub Actions will hit general availability on Nov 13. IMO, it's worth considering for this project since having multiple independent workflows offers a lot of flexibility.

**Comment by newpavlov** [comment]
@tarcieri 
I've registered for GitHub Actions, so you can try to set them up for repositories under your supervision.

**Comment by tarcieri** [comment]
@newpavlov awesome!

**Comment by tarcieri** [comment]
We switched to GitHub Actions in #103
