### ISSUE TITLE
Remove GenericArray dependency from AEAD

### ISSUE THREAD

**Issue by burdges** [RustCrypto/traits#64]
I'm tempted to use the AEAD traits, but I avoid direct dependencies on generic array when possible.  Why use it?  Is a more idiomatic approach like this workable?
```
pub trait NewAead {
    /// The size of the key array required by this algorithm.
    type Key: Default+Borrow<[u8]>+BorrowMut<[u8]>;

    /// Construct a new stateful instance for the given key.
    fn new(key: Key) -> Self;
}
```

**Comment by tarcieri** [comment]
The long-term plan for removing `generic-array` is switching to const generics.

Many of these constructions are generic over key sizes or nonce sizes:

- https://github.com/RustCrypto/AEADs/blob/master/aes-siv/src/lib.rs#L107
- https://github.com/RustCrypto/AEADs/blob/master/aes-gcm-siv/src/lib.rs#L147

Removing the current use of `generic-array` would make expressing that much more difficult, and simultaneously eliminate the type safety afforded by this approach.

**Comment by burdges** [comment]
Actually stand along associated types provide better type safety than generic array, but I found the place where @newpavlov explained the real issue: 
https://github.com/RustCrypto/traits/issues/23#issuecomment-421368665
It's extremely rare that keys, nonces, etc. exceed a `[u8; 32]` but it happens occasionally I guess. 

We've concerns about crate build times, so I prefer if generic-array never gets exposed by our own interfaces, and it make reading the code significantly harder too.  I'll maybe settle for exposing `T: NewAead`, which still incurs the build time hit, but isolates things somewhat.

**Comment by tarcieri** [comment]
> Actually stand along associated types provide marginally better type safety than generic array.

Again, the long-term plan is to move to const generics, which will provide better type safety.

I also don't see how you can capture details like "this construction can work with any AEAD with a 96-bit nonce".

> It's extremely rare that keys, nonces, etc. exceed a [u8; 32] but it happens occasionally I guess.

See the first link above to `aes-siv`: it uses 64-byte keys.

**Comment by burdges** [comment]
Appears const generics remains some ways off sadly:  https://github.com/rust-lang/rust/issues/44580 https://github.com/rust-lang/rust/labels/A-const-generics

**Comment by tarcieri** [comment]
I don't think they're so far off that making another invasive change now would make sense.

Note that all parts of the "stack" presently use `generic-array`, e.g. `aes-ctr` is built on `ctr` which implements the `stream-cipher` traits in terms of `block-cipher` impls like `aes` (not to mention `crypto-mac` and `universal-hashes`), all of which use `generic-array` to define the way they're generic over each other at their interface points.

It's pretty much "ready" for a const generics translation. Changing that would be tricky/invasive (or at best redundant), and in the end, just make it that much harder to migrate to const generics when they do eventually land.

**Comment by burdges** [comment]
I agree of course.  `[u8; SOME_LENGTH]` has numerous advantages whenever const generics eventually work.
