### ISSUE TITLE
Prefix nonces might confict with Vec-like Buffer for AEAD traits

### ISSUE THREAD

**Issue by burdges** [RustCrypto/traits#69]
Aren't nonces often handled as prefixes to ciphertext?  All AEAD trait methods assume a Vec-like buffer, but handle nonces detached, which necessitates one unnecessary allocation.  It's maybe cleaner if the detached methods work on some wrapper type over a `&'a mut [u8]`, which appears implementable with the existing `Buffer` trait, although not sure if that's the cleanest solution.

**Comment by tarcieri** [comment]
See the `xsalsa20poly1305` crate for an example of how to add an additional prefix to a message (in that case, the tag, but it works just as easily for a nonce, at the cost of a copy of the entire message).

https://github.com/RustCrypto/AEADs/blob/master/xsalsa20poly1305/src/lib.rs

No (additional) allocations are required: instead the overhead is only a copy, and the API is designed to work in heapless `no_std` environments.

The main useful optimization that isn't implemented yet is noted here as a TODO:

https://github.com/RustCrypto/AEADs/blob/d9723a1/xsalsa20poly1305/src/lib.rs#L186

Ideally both `aead` and `stream-cipher` could support an offset parameter that allows in-place encryption where the output is written at a provided offset relative to the input, which could eliminate the copy.

**Comment by burdges** [comment]
You could do this without the copy with a custom `Buffer` type per AEAD that simply reserves the correct space in the correct places, but doing this costs reallocation access.  I do not think this copy is some big deal really, but it indicates a weakness in these trait definition.

**Comment by tarcieri** [comment]
Supporting an `offset` parameter for in-place operations both eliminates the copy and is generally useful in case you'd like to encrypt/decrypt a message to a different location in the same buffer.

**Comment by burdges** [comment]
Yes true, but..  

Idiomatic rust favors offsets being encapsulated and slices representing the precise data.  If that flexibility conflicts with the idiomatic hygiene then sure flexibility wins, but actually they do not necessarily conflict because any offsets could be handled internally by some `BufferView` type:
```
pub struct BufferView<B: Borrow<[u8]>+BorrowMut<[u8]>> {
    b: B,
    nonce: usize, 
    tag: usize,
}
```
We'd create these with some `Aead::make_buffer_view` method.  I once suggested some more compressed formulation, probably overly compressed. 

Instead of what I wrote before, we avoid tying this to only `&'a mut [u8]` with `Borrow` traits, but your view into the buffer remains a `&[u8]` via `BufferView: Deref<Target=[u8]>+DerefMut` or similar.  Also, you still cannot reallocate to increase buffer size without specialization, but some other traits like maybe `Read` and `Write` traits work.

**Comment by tarcieri** [comment]
@burdges have you looked at the `heapless` integration this crate has? Here’s the `aes-gcm` crates docs for it:

https://docs.rs/aes-gcm/0.3.0/aes_gcm/#in-place-usage-eliminates-alloc-requirement

`aead::Buffer` acts as a minimal unification of `Vec` and `heapless::Vec`, and in particular leverages the `extend_from_slice` and `truncate` methods to offload length/capacity checks onto those types.

That neatly abstracts away most of the length calculation and slicing work from both AEAD consumers and AEAD implementations. When using a postfix tag.

It should also mean we can centralize all of the logic for offset handling in this crate, which should make it possible to do things like efficiently encrypt/decrypt multiple AEAD messages stored in the same buffer in-place.

**Comment by burdges** [comment]
Interesting, I suppose `heapless::Vec` might address my concerns, not the extra copies, but whatever.  

> encryption needs additional space to append the tag, which is pretty much the opposite of slicing.

I agree users cannot know how much extra space they require, which I suppose does requires special handling for `Extend` types.

After specialization lands, another crate could provide some `TryExtend` trait that expands `Extend` maybe.  

I still wonder if slicing might prove more idiomatic, but yeah the current solution seems less constrained that I thought.

**Comment by tarcieri** [comment]
> After specialization lands, another crate could provide some `TryExtend` trait that expands Extend maybe.

`TryExtend` would be nice.
