### ISSUE TITLE
Owned/`'static` version of `PasswordHash`

### ISSUE THREAD

**Issue by LukeMathWalker** [RustCrypto/traits#735]
It is currently impossible to get a `PasswordHash` with a `'static` lifetime, apart from the trivial case of a PHC string being parsed from a string literal.
This becomes an issue when storing `PasswordHash` in another struct, forcing the addition of a lifetime parameter, or when spawning threads/tasks using functions that impose a `'static` constraint (`tokio::task::spawn_blocking`).

This could be avoided by using `Cow` instead of `&str` as the underlying type for `Ident` and `Salt`. 
As a side effect, this would put the whole `PasswordHash` struct behind the `alloc` feature flag - I have very little experience with `no_std`, but I can imagine this not being desirable.

Do you see another alternative to provide an owned version of `PasswordHash`?

**Comment by tarcieri** [comment]
> This could be avoided by using Cow instead of &str as the underlying type for Ident and Salt.
As a side effect, this would put the whole PasswordHash struct behind the alloc feature flag - I have very little experience with no_std, but I can imagine this not being desirable.

The reason it works the way it does is to facilitate "heapless" usage.

> Do you see another alternative to provide an owned version of PasswordHash?

We could do something similar to the structure of the `pkcs8` crate: https://docs.rs/pkcs8/0.7.5/pkcs8/#about

...and provide a newtype for `String` which is guaranteed to parse infallibly as a `PasswordHash`.

**Comment by tarcieri** [comment]
#758 adds an owned `PasswordHashString` type
