### ISSUE TITLE
why a size of 1024 for a reader

### ISSUE THREAD

**Issue by cardoe** [RustCrypto/traits#8]
https://github.com/RustCrypto/traits/blob/4423bfd2dd410aeff3e527b17838d8fde5b7445d/digest/src/digest.rs#L72

Why are you using a size of 1024 for a reader? 4096) is typically more natural for reads. Most spinning disks implement reads of that size and that is commonly PAGE_SIZE on x86/arm (and many more architectures).

**Comment by est31** [comment]
See also #9

**Comment by newpavlov** [comment]
@cardoe 
I don' remember why exactly I chose 1kb buffer, but probably I didn't want to use 4kb of stack space for the buffer.

Probably I'll follow example of `BufReader` and will use 8kb `Box<[u8]>`. Or do you think that 4kb will be better?

**Comment by newpavlov** [comment]
I've used 8kb buffer, which is equal to std's [`DEFAULT_BUF_SIZE`](https://github.com/rust-lang/rust/blob/0be2c303692cab31390e52701007cfa87867bf74/src/libstd/sys_common/io.rs#L10). Note that in v0.8 `digest_reader` is removed in favour of `io::Read` implementation by hashers.
