### ISSUE TITLE
digest::CtOutput documentation says it requires subtle feature, but it also requires mac

### ISSUE THREAD

**Issue by nmathewson** [RustCrypto/traits#841]
Hello!

The documentation for digest::CtOutput says that it is only available when the crate is compiled with the `subtle` feature.  But it appears that you also need to compile with the `mac` feature enabled, or else CtOutput is not available.

**Comment by newpavlov** [comment]
Thank you for reporting! I will fix it right away, but since I have some doc improvements in mind, I probably will release it a bit later.
