### ISSUE TITLE
`generic-array` dependency exists despite `const_generics` being stabilized

### ISSUE THREAD

**Issue by kageru** [RustCrypto/traits#848]
While using one of your other crates (aes-gcm-siv) for a project, I noticed the complicated signatures of some key and cipher types which seem to be caused by the `generic-array` crate that was reexported by the `cipher` module in this repository.
With `const_generics` stabilized in Rust 1.51, I was wondering if that crate now offers anything that isn’t possible in standard Rust. If not, are there plans to migrate from `generic-array` to `[T; N]` types?

**Comment by newpavlov** [comment]
The stabilized const generics MVP is not sufficient for our needs. At the very least we will need stabilized [`generic_const_exprs`](https://github.com/rust-lang/rust/issues/76560). Also see RustCrypto/hashes#303.

**Comment by kageru** [comment]
I see. Thanks for the explanation.
