### ISSUE TITLE
Zeroize for GenericArray based keys

### ISSUE THREAD

**Issue by dbrgn** [RustCrypto/traits#879]
The `xsalsa20poly1305` [`Key`](https://docs.rs/xsalsa20poly1305/latest/xsalsa20poly1305/type.Key.html) is an alias for `GenericArray<u8, <Salsa<R20> as NewCipher>::KeySize>`. This means that zeroize is not used, and the key is not zeroed on drop.

I'm not too much familiar with how the different crates and traits interact, but in general it would be desirable if secret keys would be zeroized on drop. According to @tarcieri this repo is the right place to file an issue:

> it's defined at a trait-level though, so you can't just fix one crate

**Comment by newpavlov** [comment]
Right now we have the [`Key`](https://docs.rs/crypto-common/latest/crypto_common/type.Key.html) type alias built on top of the [`KeySizeUser`](https://docs.rs/crypto-common/latest/crypto_common/trait.KeySizeUser.html) trait. We could make it a wrapper type instead, but we should be careful about resulting ergonomics.

**Comment by newpavlov** [comment]
We are in the process of migrating from `generic-array` to `hybrid-array`, so I think we can close this issue.
