### ISSUE TITLE
Enable `generic-array`'s `more_lengths` feature (`digest` crate)

### ISSUE THREAD

**Issue by wtfsck** [RustCrypto/traits#890]
`generic-array`'s feature `more_lengths` enables more `Into<[T; $n]>` implementations which are useful when converting the result to an array. Right now it's only possible to do this if the hash size is at most 32 bytes. With this feature it's possible to also do it up to size 64 and some select sizes > 64, see the code below.

https://github.com/fizyk20/generic-array/blob/d4d63b7ea425f42a7e373510f95eb36ed17d34c4/src/impls.rs#L218-L251

https://github.com/RustCrypto/traits/blob/d3e544885f0f8c6bd07658470d6f5f6fd0a95b57/digest/Cargo.toml#L15

**Comment by tarcieri** [comment]
You are free to enable it yourself if you wish. That's how cargo features work.

**Comment by newpavlov** [comment]
It may be worth to enable this feature in `crypto-common`. It could simplify some of our code and improve user ergonomics, while impact on compile time should be negligible (assuming that the linked impls is the only thing enabled by this feature).

**Comment by wtfsck** [comment]
I'm not using `generic-array` directly, only indirectly through the  sha2 crate. It depends on digest which does not enable the feature.

Adding `generic-array` to my own crate so this feature can be enabled in a dependency of a dependency works but is a hack, and it will probably stop working when digest bumps its version to eg. 0.15 while my crate still uses the 0.14 (latest at this time).
