### ISSUE TITLE
Digest should impl Writer instead of digest_reader

### ISSUE THREAD

**Issue by est31** [RustCrypto/traits#9]
It would be cool if the digest trait could impl std::io::Writer so that you can use std::io::copy to copy over stuff from a reader. This is better than implementing the function yourself and calling it `digest_reader` :).

**Comment by tarcieri** [comment]
Relying on traits from `std::io` is super annoying for `no_std` users

**Comment by est31** [comment]
@tarcieri right, so do it like it is done for `digest_reader`: make it optional, depending on whether the `std` feature is enabled or not. I've thought that this was obvious otherwise I'd have said it, sorry :).

**Comment by tarcieri** [comment]
So long as it isn't a fundamental part of the API that's okay (reliance on `std::io` traits and types is a huge blocker to adding `no_std` support to several other crates)

**Comment by newpavlov** [comment]
Unfortunately I can't write `impl<D: Input> io::Write for D { .. }` in the `digest` crate due to the Rust coherence rules, this is why `digest_reader` was introduced. The only way to implement `io::Write` is to do it directly over concrete hasher types.

**Comment by est31** [comment]
Oh I see. An alternative is that the digest crate exposes a macro that impl's the trait and the hasher types then use that macro.

**Comment by newpavlov** [comment]
Fixed with `digest v0.8`. All hashes implement `std::io::Write` with enabled `std` feature.
