### ISSUE TITLE
`ExpandMsg` hidden

### ISSUE THREAD

**Issue by daxpedda** [RustCrypto/traits#901]
Currently `ExpandMsgXmd` or `ExpandMsgXof` are needed to use anything in `GroupDigest`, but they are all hidden in the `hash2field` module and not visible in the documentation.

I propose re-exporting them from inside the `hash2curve` module. Willing to do the PR upon approval.

**Comment by tarcieri** [comment]
Sounds fine to me

**Comment by mikelodder7** [comment]
Yep sounds great
