### ISSUE TITLE
DigestSigner security and workarounds

### ISSUE THREAD

**Issue by nickray** [RustCrypto/traits#980]
Trying to understand the implications of https://docs.rs/signature/latest/signature/trait.DigestSigner.html regarding security + practicality.

First, are there concrete examples and/or references to explain the concrete dangers involved in signing raw digest bytes?

Secondly, it's somewhat easy to workaround: https://gist.github.com/nickray/b9e091c075f174abcf382bce684e0ba7; this is kind of dirty as the signing implementation itself uses the Digest for both picking off the input (without an additional finalize step when using Fake256) and the hash-and-pray style of constructions to make a deterministic signature. In any case, this seems to implement `sign_digest ∘ digest = sign`.

For context, I have a trusted client (in Go), which produces hashes to be signed (as prehashed signatures). To explain this in a little more detail, it's a private Cosmos blockchain which my signing services polls. I potentially could teach the client to make signatures requests with the full message, but this is a little wasteful, given I already trust it.

Would it make sense to have a kind of `signature::hazmat::RawDigestSigner`?

**Comment by tarcieri** [comment]
> First, are there concrete examples and/or references to explain the concrete dangers involved in signing raw digest bytes?

The main risk would be someone doing both: signing and verifying raw bytes, in which case an attacker can trivially craft a signature for any message they want.

Separately, there's the issue that the RFC6979 implementation sources the digest to use from `DigestSigner`.

> Would it make sense to have a kind of signature::hazmat::RawDigestSigner?

We could potentially change `SignPrimitive::try_sign_prehashed` to accept raw bytes and perform a reduction to a scalar internally

**Comment by tarcieri** [comment]
My main general recommendation is to use an inherent method or internal trait for this functionality. I don't think it makes sense to have traits for it in the `signature` crate.

What's the use case for *generically* signing digest outputs?
