### ISSUE TITLE
digest: Create mid-level trait for `new_with_prefix` (e.g PrefixInit)

### ISSUE THREAD

**Issue by yokomizor** [RustCrypto/traits#983]
Hi there (:

# Question:

What is the purpose of `Digest::new_with_prefix`?
I assume the main use case would be to derive a key for some context (1). Please let me know if not.

# Problem:

`Digest::new_with_prefix` makes no assumption on what prefix actually means.

If (1) is correct, then the prefix would be the context, and  the key material would be digested next, producing the new derived key. 

Currently, the `Digest` trait implements a very handy default. It just absorbs the prefix using `Update::update`:

https://github.com/RustCrypto/traits/blob/34540dcd05e3f7337a9cf322999520f5aea6f759/digest/src/digest.rs#L64-L71

This default is very handy. However, sometimes it might be desirable to have some sort of domain separation between the prefix (context) and the actual data to be digested. One example would be BLAKE3::derive_key:

https://github.com/BLAKE3-team/BLAKE3/blob/b776e8f32885b58b850c03ccdb66c72dfb404459/src/lib.rs#L978-L984

It uses the prefix to define the initialisation vector.

Now compare the generic BLAKE3 version, where the IV is hard coded:

https://github.com/BLAKE3-team/BLAKE3/blob/b776e8f32885b58b850c03ccdb66c72dfb404459/src/lib.rs#L960-L962

Still assuming (1) is correct, how to implement  the `Digest` trait for `blake3::Hasher` so `Digest::new_with_prefix` would use `blake3::Hasher::derive_key` instead of `blake3::Hasher::new` followed by `blake3::Hasher::update`?

I am not aware of any way to overwrite the default implementation of `Digest::new_with_prefix` if a type already implements the mid-level traits, since it would conflict with the generic implementation:

```
   = note: conflicting implementation in crate `digest`:
           - impl<D> Digest for D
             where D: FixedOutput, D: Default, D: Update, D: HashMarker;
```

One alternative would be to wrap the type implementing the mid-level traits and implement only the high-level trait for the wrapper type, calling the wrapped type manually, which IMO would defeat the purpose of mid-level traits.

# Suggestions

**Suggestion 1:**

If (1) is correct and (1) is the only use case for `Digest::new_with_prefix`:

- Deprecate `Digest::new_with_prefix`.
- Create a high-level `HKDF` trait, or point to the `HKDF` trait documentation if one already exists.

**Suggestion 2:**

If (1) is correct, but there are different use cases for `Digest::new_with_prefix`:

- Remove the `Digest::new_with_prefix` default implementation.
- Create a mid-level `PrefixInit` trait.
- Define `DynDigest::new_with_prefix` for consistency.

**Suggestion 3:**

If (1) is incorrect:

- Document `Digest::new_with_prefix` should not be used as HKDF.
- Define `DynDigest::new_with_prefix` for consistency.

**Comment by tarcieri** [comment]
In general, Digests have many other uses besides key derivation.

`Digest::new_with_prefix` is also useful for things other than a context/domain separator. It's useful anywhere you'd like to hash a message and return the `Digest` instance. Here's a real-world example:

https://github.com/RustCrypto/traits/blob/master/signature/derive/src/lib.rs#L63

That said, it's also useful for initializing a digest with some leading context as you mention. Ideally we could make such functionality `const fn` so it's possible to initialize and store a digest in an initial state at compile time.

> Create a high-level HKDF trait, or point to the HKDF trait documentation if one already exists.

We don't currently provide KDF traits, though that would be nice to have. See this issue: https://github.com/RustCrypto/traits/issues/5

**Comment by tarcieri** [comment]
> Others might assume prefix is the context in a HKDF, where domain separation is desired.

`Digest` is at a much lower level than a KDF. The typical name for a domain separation string like this on a digest function is a "personalization string".

That said I think there's an argument to be made that someone might confuse it for something like a personalization string.

**Comment by yokomizor** [comment]
Got it.

I thought the `PrefixInit` would be a good idea since there is already the `KeyInit` trait, but now I realised that it would only make sense if a `KDF` trait is also provided (or at least a `KDFMarker`).

Now I understand that `D::new_with_prefix(b"prefix")` is just an alias to `D::new().chain_update(b"prefix")`, so I am closing this issue.

Thanks for this crate!

cheer

**Comment by newpavlov** [comment]
See #5 for discussion of potential KDF traits.

**Comment by yokomizor** [comment]
Thanks @newpavlov. I have checked, but I don't have much to add there. The discussion seems to be about creating (and naming) KDF traits that would cover all cases.

What I was looking for, was way simpler: just a way to use implementors of `Digest` as a KDF for ephemeral keys.

I needed a simple trait for a function that receives a KDF, and calls it passing a context and some AAD to generate some ephemeral keys. I thought I could use `Digest::new_with_prefix`, but @tarcieri already explained me that that is not the case.

I will keep an eye on https://github.com/RustCrypto/traits/issues/5 anyway. Thanks!
