### ISSUE TITLE
`DynDigest` is not `Send`

### ISSUE THREAD

**Issue by BenJeau** [RustCrypto/traits#984]
I've discovered that `DynDigest` is not `Send` when trying to use `librespot` with a crate (`swift-bridge`) requiring async functions to be `Send`.

https://github.com/chinedufn/swift-bridge/issues/50#issuecomment-1104625311

Is it possible to make `DynDigest` `Send`? (since I'm unsure of what `Send` is, let me know if I'm totally wrong for asking `DynDigest` to be `Send`)

**Comment by tarcieri** [comment]
`DynDigest` and `Send` are both traits.

If you want a type that's both, you need to bound on both, either `T: DynDigest + Send`, or `&(dyn DynDigest + Send)` for a trait object.

**Comment by BenJeau** [comment]
Thanks for the clarification :)
